'use strict';
// Opt-in: a disposable PostgreSQL 16 database with DB-P2, SEC-P3, and SEC-P5 applied.
const test = require('node:test'); const assert = require('node:assert/strict'); const { Client, Pool } = require('pg');
const { PostgresBirthProfileRepository, PostgresReadingRepository, PostgresEntitlementRepository } = require('../../src/persistence');
const { BirthProfilePayloadCodec, ReadingPayloadCodec, PostgresUserKeyEnvelopeStore, UserDekProvider } = require('../../src/security/crypto');
const { PostgresApplicationTransactionExecutor, SecureReadingService } = require('../../src/application/readings'); const { runWithAuthenticatedDbContext } = require('../../src/security/database-context'); const { TestOnlyKms } = require('./crypto/test-only-kms');
const { BirthCareerReadingOrchestrator } = require('../../src/orchestration'); const { createResolvedBirthPlace } = require('../../src/place'); const { createReadingRecord, replayPersistedReading } = require('../../src/readings'); const { deepFreeze } = require('../../src/astronomy');
const connectionString = process.env.KUNDLINSIGHTS_SEC_P6_DATABASE_URL; const T0 = '2026-08-13T00:00:00.000Z'; const BIRTH = '1990-11-26T08:10:00.000Z'; const SAVANA = 'vimshottari-longitude-proportional-savana-360-v1'; const SOLAR = 'vimshottari-longitude-proportional-solar-return-v1';
const principal = (subject) => ({ provider: 'supabase', subject, isAnonymous: false }); const birthData = { localDate: '1990-11-26', localTime: '13:40:00', timezone: 'Asia/Kolkata', utc: BIRTH, latitude: 17.385, longitude: 78.4867, timezoneProvenance: { provider: 'timezone-boundary-builder', datasetVersion: '2026c', datasetChecksum: 'test' } }; const LONGITUDES = Object.freeze({ Sun: 220.07412509999472, Moon: 319.51986976098, Mars: 180.3, Mercury: 210.4, Jupiter: 275.5, Venus: 300.6, Saturn: 225.7, Rahu: 90.8, Ketu: 270.8, Ascendant: 330.9 });
async function crypto(pool, subject, operation) { return runWithAuthenticatedDbContext({ db: pool, authSubject: subject, operation: async (db) => { await db.query('set local role app_crypto'); return operation(db); } }); }
function envelopeStore(pool, subject) { const call = (method, input) => crypto(pool, subject, (db) => new PostgresUserKeyEnvelopeStore({ db })[method](input)); return { getActiveEnvelope: (v) => call('getActiveEnvelope', v), getEnvelopeByVersion: (v) => call('getEnvelopeByVersion', v), insertEnvelope: (v) => call('insertEnvelope', v), rotateEnvelope: (v) => call('rotateEnvelope', v) }; }
function provider(pool, subject, kms, prefix) { let n = 0; return new UserDekProvider({ kms, envelopeStore: envelopeStore(pool, subject), idGenerator: () => `${prefix}-${++n}`, now: () => T0 }); }
function astronomyEngine() { const bodies = deepFreeze(Object.fromEntries(Object.entries(LONGITUDES).map(([body, siderealLongitudeDegrees]) => [body, deepFreeze({ body, siderealLongitudeDegrees, tropicalLongitudeDegrees: null, longitudeSpeedDegreesPerDay: body === 'Ascendant' ? null : 1, motion: body === 'Ascendant' ? null : 'direct', siderealMetadata: deepFreeze({ siderealMode: 'SE_SIDM_LAHIRI', calculationStatus: 'TEST_ONLY' }), provenance: deepFreeze({ coordinateProvenance: 'provider-native' }) })]))); return { calculate() { return deepFreeze({ bodies, instant: deepFreeze({ utc: BIRTH, unixMilliseconds: Date.parse(BIRTH) }), sidereal: deepFreeze({ siderealMode: 'SE_SIDM_LAHIRI' }), provider: deepFreeze({ providerId: 'synthetic-sec-p6-test', calculationStatus: 'TEST_ONLY', siderealMode: 'SE_SIDM_LAHIRI', nodeModel: 'MEAN_NODE', productionLicenseGate: false }) }); } }; }
function sunSampler() { return deepFreeze({ sampleCanonicalSiderealSun({ instantUtc }) { return deepFreeze({ canonicalSiderealLongitudeDegrees: ((LONGITUDES.Sun + (Date.parse(instantUtc) - Date.parse(BIRTH)) * 360 / (365 * 86400000)) % 360 + 360) % 360, provenance: deepFreeze({ providerId: 'synthetic-sec-p6-test', calculationStatus: 'TEST_ONLY', siderealMode: 'SE_SIDM_LAHIRI', coordinateProvenance: 'provider-native', productionAuthority: false }) }); } }); }
function place(data = birthData) { return deepFreeze(createResolvedBirthPlace({ provider: 'persisted-sec-p6', providerPlaceId: 'profile-place', latitude: data.latitude, longitude: data.longitude, timezone: data.timezone, timezoneResolver: data.timezoneProvenance })); }
function input(data = birthData) { const resolved = place(data); return { birth: { localDate: data.localDate, localTime: data.localTime, timezone: data.timezone, utc: data.utc, latitude: data.latitude, longitude: data.longitude, placeResolution: { resolutionVersion: resolved.resolutionVersion, timezoneResolver: data.timezoneProvenance }, display: null }, readingInstant: T0, transitScanRange: null, locale: 'en-IN' }; }
function result(data, ruleset) { return new BirthCareerReadingOrchestrator({ astronomicalEngine: astronomyEngine(), dashaRulesetId: ruleset, ...(ruleset === SOLAR ? { canonicalSiderealSunSampler: sunSampler() } : {}) }).generate({ birth: { date: data.localDate, time: data.localTime, place: place(data) }, readingInstant: T0, locale: 'en-IN' }); }

test('SEC-P6 real Savana replay, default Solar generation, and concurrent idempotent generation remain encrypted and RLS-owned', { skip: !connectionString }, async () => {
  const admin = new Client({ connectionString }); const bootstrapPool = new Pool({ connectionString, max: 4 }); let serverPool; await admin.connect();
  try {
    await admin.query('drop role if exists sec_p6_server'); await admin.query('create role sec_p6_server login nosuperuser nobypassrls nocreatedb nocreaterole noinherit'); await admin.query('grant app_runtime, app_worker, app_crypto to sec_p6_server');
    await admin.query('truncate app.user_key_envelopes, app.reading_records, app.entitlements, app.payment_transactions, app.birth_profiles, app.users'); await admin.query("insert into app.users (id,auth_subject,status,created_at,updated_at) values ('user-a','subject-a','active',$1,$1),('user-b','subject-b','active',$1,$1)", [T0]); await bootstrapPool.end();
    serverPool = new Pool({ connectionString: connectionString.replace('postgresql:///', 'postgresql://sec_p6_server@/'), max: 5 }); const role = await serverPool.query("select session_user, rolsuper, rolbypassrls from pg_roles where rolname=session_user"); assert.deepEqual(role.rows[0], { session_user: 'sec_p6_server', rolsuper: false, rolbypassrls: false });
    const kms = new TestOnlyKms(); const deksA = provider(serverPool, 'subject-a', kms, 'a'); const deksB = provider(serverPool, 'subject-b', kms, 'b'); await deksA.provisionUserDek('user-a'); await deksB.provisionUserDek('user-b'); const birthCodecA = new BirthProfilePayloadCodec({ userDekProvider: deksA }); const readingCodecA = new ReadingPayloadCodec({ userDekProvider: deksA }); const birthCodecB = new BirthProfilePayloadCodec({ userDekProvider: deksB });
    await runWithAuthenticatedDbContext({ db: serverPool, authSubject: 'subject-a', operation: async (db) => { await db.query('set local role app_runtime'); await new PostgresBirthProfileRepository({ db, birthProfilePayloadCodec: birthCodecA }).createBirthProfile({ id: 'profile-a', userId: 'user-a', birthData, createdAt: T0 }); } });
    await runWithAuthenticatedDbContext({ db: serverPool, authSubject: 'subject-b', operation: async (db) => { await db.query('set local role app_runtime'); await new PostgresBirthProfileRepository({ db, birthProfilePayloadCodec: birthCodecB }).createBirthProfile({ id: 'profile-b', userId: 'user-b', birthData, createdAt: T0 }); } });
    const savana = createReadingRecord({ readingId: 'historical-savana-abcdefgh', createdAt: T0, input: input(), result: result(birthData, SAVANA) });
    await runWithAuthenticatedDbContext({ db: serverPool, authSubject: 'subject-a', operation: async (db) => { await db.query('set local role app_runtime'); await new PostgresReadingRepository({ db, readingPayloadCodec: readingCodecA }).insertReadingRecord({ userId: 'user-a', birthProfileId: 'profile-a', record: savana, idempotencyKey: 'historical-savana' }); } });
    await admin.query("insert into app.entitlements (id,user_id,product_key,status,quantity,valid_from,valid_until,source_payment_transaction_id,created_at,updated_at) values ('ent-a','user-a','CAREER','active',3,$1,null,null,$1,$1)", [T0]);
    let ids = 0; const service = new SecureReadingService({ authUserResolver: async (p) => ({ id: p.subject === 'subject-a' ? 'user-a' : 'user-b', status: 'active' }), transactionExecutor: new PostgresApplicationTransactionExecutor({ db: serverPool }), repositories: ({ db }) => ({ birthProfiles: new PostgresBirthProfileRepository({ db, birthProfilePayloadCodec: birthCodecA }), readings: new PostgresReadingRepository({ db, readingPayloadCodec: readingCodecA }), entitlements: new PostgresEntitlementRepository({ db }) }), readingGenerator: { generate: async ({ birthProfile }) => ({ input: input(birthProfile.birthData), result: result(birthProfile.birthData, SOLAR) }) }, readingRecordFactory: createReadingRecord, replayReading: replayPersistedReading, requiresEntitlement: () => true, idGenerator: () => `solar-secure-${++ids}-abcdefgh`, clock: () => T0 });
    const historical = await service.replaySecureReading({ principal: principal('subject-a'), readingId: savana.readingId, astronomicalRuntime: { astronomicalEngine: astronomyEngine() } }); assert.equal(historical.replay.result.provenance.engineProfileId, 'kundlinsights-vedic-engine-profile-v1'); assert.equal(historical.replay.result.provenance.dashaRulesetId, SAVANA); assert.equal(historical.replay.result.provenance.timezoneDatasetVersion, '2026c');
    const request = { principal: principal('subject-a'), birthProfileId: 'profile-a', domain: 'CAREER', idempotencyKey: 'solar-secure-request', readingInstant: T0, locale: 'en-IN' }; const solar = await service.generateSecureReading(request); const fetched = await service.getSecureReading({ principal: principal('subject-a'), readingId: solar.readingId }); const replayed = await service.replaySecureReading({ principal: principal('subject-a'), readingId: solar.readingId, astronomicalRuntime: { astronomicalEngine: astronomyEngine(), canonicalSiderealSunSampler: sunSampler() } }); assert.equal(fetched.record.engineProfileId, 'kundlinsights-vedic-engine-profile-v2'); assert.equal(replayed.replay.result.provenance.dashaRulesetId, SOLAR); assert.equal(fetched.record.input.birth.placeResolution.timezoneResolver.datasetVersion, '2026c'); assert.equal(JSON.stringify(fetched).includes('ciphertext'), false);
    await assert.rejects(service.generateSecureReading({ ...request, principal: principal('subject-b'), birthProfileId: 'profile-a', idempotencyKey: 'forbidden-profile' }), (e) => e && e.code === 'NOT_FOUND_OR_FORBIDDEN'); await assert.rejects(service.getSecureReading({ principal: principal('subject-b'), readingId: solar.readingId }), (e) => e && e.code === 'NOT_FOUND_OR_FORBIDDEN');
    const before = Number((await admin.query("select quantity from app.entitlements where id='ent-a'")).rows[0].quantity); const duplicate = { ...request, idempotencyKey: 'concurrent-secure-request' }; const outcomes = await Promise.all([service.generateSecureReading(duplicate), service.generateSecureReading(duplicate)]); assert.equal(outcomes[0].readingId, outcomes[1].readingId); assert.equal(Number((await admin.query("select count(*) from app.reading_records where user_id='user-a' and idempotency_key='concurrent-secure-request'")).rows[0].count), 1); assert.equal(before - Number((await admin.query("select quantity from app.entitlements where id='ent-a'")).rows[0].quantity), 1);
    kms.setCurrentKeyVersion('test-kek-v2'); await deksA.rotateUserDek('user-a'); assert.equal((await service.replaySecureReading({ principal: principal('subject-a'), readingId: savana.readingId, astronomicalRuntime: { astronomicalEngine: astronomyEngine() } })).replay.result.provenance.dashaRulesetId, SAVANA); const afterRotation = await service.generateSecureReading({ ...request, idempotencyKey: 'solar-after-rotation' }); assert.equal((await admin.query('select payload_key_version from app.reading_records where id=$1', [afterRotation.readingId])).rows[0].payload_key_version, 'test-kek-v2');
  } finally { await serverPool?.end(); await bootstrapPool.end().catch(() => {}); await admin.query('drop role if exists sec_p6_server').catch(() => {}); await admin.end(); }
});
