'use strict';
// Opt-in: a disposable local DB with DB-P2, SEC-P3, and SEC-P5 migrations applied.
const test = require('node:test'); const assert = require('node:assert/strict'); const { Client, Pool } = require('pg');
const { runWithAuthenticatedDbContext } = require('../../src/security/database-context');
const { PostgresUserKeyEnvelopeStore, UserDekProvider, ReadingPayloadCodec } = require('../../src/security/crypto');
const { PostgresReadingRepository } = require('../../src/persistence'); const { TestOnlyKms } = require('./crypto/test-only-kms');
const { BirthCareerReadingOrchestrator } = require('../../src/orchestration'); const { createResolvedBirthPlace } = require('../../src/place'); const { deepFreeze } = require('../../src/astronomy'); const { createReadingRecord, replayPersistedReading } = require('../../src/readings');
const connectionString = process.env.KUNDLINSIGHTS_SEC_P5_DATABASE_URL; const T0 = '2026-08-13T00:00:00.000Z'; const BIRTH = '1990-11-26T08:10:00.000Z'; const SAVANA = 'vimshottari-longitude-proportional-savana-360-v1'; const SOLAR = 'vimshottari-longitude-proportional-solar-return-v1';
const LONGITUDES = Object.freeze({ Sun: 220.07412509999472, Moon: 319.51986976098, Mars: 180.3, Mercury: 210.4, Jupiter: 275.5, Venus: 300.6, Saturn: 225.7, Rahu: 90.8, Ketu: 270.8, Ascendant: 330.9 });
async function asCrypto(pool, authSubject, operation) { return runWithAuthenticatedDbContext({ db: pool, authSubject, operation: async (client) => { await client.query('set local role app_crypto'); return operation(client); } }); }
async function asRuntime(pool, authSubject, operation) { return runWithAuthenticatedDbContext({ db: pool, authSubject, operation: async (client) => { await client.query('set local role app_runtime'); return operation(client); } }); }
function cryptoStore(pool, authSubject) { const run = (method, input) => asCrypto(pool, authSubject, (db) => new PostgresUserKeyEnvelopeStore({ db })[method](input)); return { getActiveEnvelope: (v) => run('getActiveEnvelope', v), getEnvelopeByVersion: (v) => run('getEnvelopeByVersion', v), insertEnvelope: (v) => run('insertEnvelope', v), rotateEnvelope: (v) => run('rotateEnvelope', v) }; }
function ids(prefix) { let n = 0; return () => `${prefix}-${++n}`; }
function provider(pool, subject, kms, prefix) { return new UserDekProvider({ kms, envelopeStore: cryptoStore(pool, subject), idGenerator: ids(prefix), now: () => T0 }); }
function astronomyEngine() { const bodies = deepFreeze(Object.fromEntries(Object.entries(LONGITUDES).map(([body, siderealLongitudeDegrees]) => [body, deepFreeze({ body, siderealLongitudeDegrees, tropicalLongitudeDegrees: null, longitudeSpeedDegreesPerDay: body === 'Ascendant' ? null : 1, motion: body === 'Ascendant' ? null : 'direct', siderealMetadata: deepFreeze({ siderealMode: 'SE_SIDM_LAHIRI', calculationStatus: 'TEST_ONLY' }), provenance: deepFreeze({ coordinateProvenance: 'provider-native' }) })]))); return { calculate() { return deepFreeze({ bodies, instant: deepFreeze({ utc: BIRTH, unixMilliseconds: Date.parse(BIRTH) }), sidereal: deepFreeze({ siderealMode: 'SE_SIDM_LAHIRI' }), provider: deepFreeze({ providerId: 'synthetic-sec-p5-test', calculationStatus: 'TEST_ONLY', siderealMode: 'SE_SIDM_LAHIRI', nodeModel: 'MEAN_NODE', productionLicenseGate: false }) }); } }; }
function sunSampler() { return deepFreeze({ sampleCanonicalSiderealSun({ instantUtc }) { return deepFreeze({ canonicalSiderealLongitudeDegrees: ((LONGITUDES.Sun + (Date.parse(instantUtc) - Date.parse(BIRTH)) * 360 / (365 * 86400000)) % 360 + 360) % 360, provenance: deepFreeze({ providerId: 'synthetic-sec-p5-test', calculationStatus: 'TEST_ONLY', siderealMode: 'SE_SIDM_LAHIRI', coordinateProvenance: 'provider-native', productionAuthority: false }) }); } }); }
function readingRecord(ruleset) { const place = deepFreeze(createResolvedBirthPlace({ provider: 'test', providerPlaceId: 'sec-p5-place', latitude: 17.385, longitude: 78.4867, timezone: 'Asia/Kolkata', timezoneResolver: { provider: 'timezone-boundary-builder', datasetVersion: '2026c', datasetChecksum: 'test' } })); const result = new BirthCareerReadingOrchestrator({ astronomicalEngine: astronomyEngine(), dashaRulesetId: ruleset, ...(ruleset === SOLAR ? { canonicalSiderealSunSampler: sunSampler() } : {}) }).generate({ birth: { date: '1990-11-26', time: '13:40:00', place }, readingInstant: T0, locale: 'en-IN' }); return createReadingRecord({ readingId: ruleset === SAVANA ? 'reading-savana-v1' : 'reading-solar-v2', createdAt: T0, input: { birth: { localDate: '1990-11-26', localTime: '13:40:00', timezone: 'Asia/Kolkata', utc: BIRTH, latitude: 17.385, longitude: 78.4867, placeResolution: { resolutionVersion: place.resolutionVersion, timezoneResolver: place.timezoneResolver }, display: { label: 'Synthetic Hyderabad' } }, readingInstant: T0, transitScanRange: null, locale: 'en-IN' }, result }); }

test('SEC-P5 persists and rotates envelopes with RLS, absence isolation, and real concurrent provisioning safety', { skip: !connectionString }, async () => {
  const admin = new Client({ connectionString }); const pool = new Pool({ connectionString, max: 3 }); await admin.connect();
  try {
    await admin.query('truncate app.user_key_envelopes, app.reading_records, app.entitlements, app.payment_transactions, app.birth_profiles, app.users'); await admin.query("insert into app.users (id,auth_subject,status,created_at,updated_at) values ('user-a','subject-a','active',$1,$1),('user-b','subject-b','active',$1,$1),('user-race','subject-race','active',$1,$1)", [T0]);
    const kms = new TestOnlyKms(); const first = provider(pool, 'subject-race', kms, 'race-one'); const second = provider(pool, 'subject-race', kms, 'race-two'); const race = await Promise.allSettled([first.provisionUserDek('user-race'), second.provisionUserDek('user-race')]);
    assert.equal(race.filter((result) => result.status === 'fulfilled').length, 1); assert.equal(race.filter((result) => result.status === 'rejected' && result.reason.code === 'ACTIVE_KEY_ENVELOPE_EXISTS').length, 1);
    assert.equal((await admin.query("select count(*)::int as count from app.user_key_envelopes where user_id='user-race' and status='active'")).rows[0].count, 1);
    const userAProvider = provider(pool, 'subject-a', kms, 'a'); await userAProvider.provisionUserDek('user-a');
    const userBProvider = provider(pool, 'subject-b', kms, 'b'); await userBProvider.provisionUserDek('user-b');
    await asCrypto(pool, 'subject-a', async (db) => assert.equal((await new PostgresUserKeyEnvelopeStore({ db }).getActiveEnvelope({ userId: 'user-a' })).userId, 'user-a'));
    await asCrypto(pool, 'subject-b', async (db) => assert.equal(await new PostgresUserKeyEnvelopeStore({ db }).getActiveEnvelope({ userId: 'user-a' }), null));
    await assert.rejects(asRuntime(pool, 'subject-a', async (db) => db.query('select * from app.user_key_envelopes')), (e) => e && e.code === 'AUTHENTICATED_DB_OPERATION_FAILED');
    const client = await pool.connect(); try { await client.query('begin'); await client.query('set local role app_crypto'); assert.equal(await new PostgresUserKeyEnvelopeStore({ db: client }).getActiveEnvelope({ userId: 'user-a' }), null); await client.query('commit'); } finally { client.release(); }
    await asCrypto(pool, 'unknown-subject', async (db) => assert.equal(await new PostgresUserKeyEnvelopeStore({ db }).getActiveEnvelope({ userId: 'user-a' }), null));
    await asCrypto(pool, 'subject-a', async (db) => assert.equal((await new PostgresUserKeyEnvelopeStore({ db }).getActiveEnvelope({ userId: 'user-a' })).userId, 'user-a'));
    const reused = await pool.connect(); try {
      await reused.query('begin'); await reused.query('set local role app_crypto'); await reused.query("select set_config('app.auth_subject', 'subject-a', true)");
      const storeA = new PostgresUserKeyEnvelopeStore({ db: reused }); const envelopeA = await storeA.getActiveEnvelope({ userId: 'user-a' });
      assert.equal(envelopeA.userId, 'user-a'); assert.equal(await storeA.getActiveEnvelope({ userId: 'user-b' }), null); await reused.query('commit');
      await reused.query('begin'); await reused.query('set local role app_crypto');
      const storeWithoutSubject = new PostgresUserKeyEnvelopeStore({ db: reused }); assert.equal(await storeWithoutSubject.getActiveEnvelope({ userId: 'user-a' }), null); assert.equal(await storeWithoutSubject.getActiveEnvelope({ userId: 'user-b' }), null); await reused.query('commit');
      await reused.query('begin'); await reused.query('set local role app_crypto'); await reused.query("select set_config('app.auth_subject', 'subject-b', true)");
      const storeB = new PostgresUserKeyEnvelopeStore({ db: reused }); const envelopeB = await storeB.getActiveEnvelope({ userId: 'user-b' });
      assert.equal(envelopeB.userId, 'user-b'); assert.notEqual(envelopeA.id, envelopeB.id); assert.notEqual(envelopeA.userId, envelopeB.userId); assert.deepEqual(envelopeB.wrappedDek, (await storeB.getEnvelopeByVersion({ userId: 'user-b', keyVersion: envelopeB.keyVersion })).wrappedDek); assert.equal(await storeB.getActiveEnvelope({ userId: 'user-a' }), null); await reused.query('commit');
    } finally { reused.release(); }
  } finally { await pool.end(); await admin.end(); }
});

test('SEC-P5 persisted Postgres envelopes preserve Savana V1 and Solar V2 replay across rotation', { skip: !connectionString }, async () => {
  const admin = new Client({ connectionString }); const pool = new Pool({ connectionString, max: 3 }); await admin.connect();
  try {
    await admin.query('truncate app.user_key_envelopes, app.reading_records, app.entitlements, app.payment_transactions, app.birth_profiles, app.users'); await admin.query("insert into app.users (id,auth_subject,status,created_at,updated_at) values ('user-a','subject-a','active',$1,$1)", [T0]);
    const kms = new TestOnlyKms(); const deks = provider(pool, 'subject-a', kms, 'replay'); await deks.provisionUserDek('user-a'); const codec = new ReadingPayloadCodec({ userDekProvider: deks }); const savana = readingRecord(SAVANA);
    await asRuntime(pool, 'subject-a', async (db) => { const readings = new PostgresReadingRepository({ db, readingPayloadCodec: codec }); await readings.insertReadingRecord({ userId: 'user-a', birthProfileId: null, record: savana }); });
    kms.setCurrentKeyVersion('test-kek-v2'); await deks.rotateUserDek('user-a'); const solar = readingRecord(SOLAR);
    await asRuntime(pool, 'subject-a', async (db) => { const readings = new PostgresReadingRepository({ db, readingPayloadCodec: codec }); await readings.insertReadingRecord({ userId: 'user-a', birthProfileId: null, record: solar }); const old = await readings.getReadingRecord(savana.readingId); const current = await readings.getReadingRecord(solar.readingId); assert.equal(replayPersistedReading({ record: old.record, astronomicalRuntime: { astronomicalEngine: astronomyEngine() } }).result.provenance.dashaRulesetId, SAVANA); assert.equal(replayPersistedReading({ record: current.record, astronomicalRuntime: { astronomicalEngine: astronomyEngine(), canonicalSiderealSunSampler: sunSampler() } }).result.provenance.dashaRulesetId, SOLAR); assert.equal(old.record.engineProfileId, 'kundlinsights-vedic-engine-profile-v1'); assert.equal(current.record.engineProfileId, 'kundlinsights-vedic-engine-profile-v2'); assert.equal(old.record.input.birth.placeResolution.timezoneResolver.datasetVersion, '2026c'); assert.equal(current.record.input.birth.timezone, 'Asia/Kolkata'); });
    const versions = await admin.query("select id,payload_key_version from app.reading_records order by id"); assert.deepEqual(versions.rows.map((row) => [row.id, row.payload_key_version]), [['reading-savana-v1', 'test-kek-v1'], ['reading-solar-v2', 'test-kek-v2']]);
  } finally { await pool.end(); await admin.end(); }
});
