'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { AwsKmsProvider, WRAPPING_ALGORITHM } = require('../../../src/security/crypto');
const ARN = 'arn:aws:kms:ap-south-1:123456789012:key/11111111-1111-1111-1111-111111111111'; const OLD = 'arn:aws:kms:ap-south-1:123456789012:key/22222222-2222-2222-2222-222222222222'; const DEK = Buffer.alloc(32, 7);
function client(handler) { return { async send(command) { return handler(command); } }; }
test('AWS KMS provider wraps and unwraps DEKs with only privacy-safe stable context', async () => { const commands=[]; const kms=new AwsKmsProvider({client:client((command)=>{commands.push(command.input); return command.input.Plaintext ? {CiphertextBlob:Buffer.from('cipher')} : {Plaintext:DEK};}),kmsKeyArn:ARN,keyVersionGenerator:()=> 'envelope-1'}); assert.equal(kms.getCurrentKeyVersion(),'envelope-1'); assert.deepEqual(kms.getWrappingMetadata({keyVersion:'envelope-1'}),{kmsKeyRef:ARN,wrappingAlgorithm:WRAPPING_ALGORITHM}); const cipher=await kms.wrapDek({keyVersion:'envelope-1',dek:DEK}); assert.deepEqual(cipher,Buffer.from('cipher')); const plain=await kms.unwrapDek({keyVersion:'envelope-1',kmsKeyRef:ARN,wrappingAlgorithm:WRAPPING_ALGORITHM,wrappedDek:cipher}); assert.deepEqual(plain,DEK); assert.deepEqual(commands[0].EncryptionContext,{application:'kundlinsights',purpose:'user-dek-wrap-v1',envelopeVersion:'envelope-1'}); assert.equal(JSON.stringify(commands[0]).includes('userId'),false); });
test('AWS KMS provider uses persisted historical KMS references and fails closed', async () => { const calls=[]; const kms=new AwsKmsProvider({client:client((command)=>{calls.push(command.input); if(command.input.CiphertextBlob) return {Plaintext:DEK}; throw new Error('provider details');}),kmsKeyArn:ARN,historicalKmsKeyArns:[OLD]}); await kms.unwrapDek({keyVersion:'old-envelope',kmsKeyRef:OLD,wrappingAlgorithm:WRAPPING_ALGORITHM,wrappedDek:Buffer.from('x')}); assert.equal(calls[0].KeyId,OLD); await assert.rejects(kms.wrapDek({keyVersion:'x',dek:Buffer.alloc(31)}),e=>e.code==='DEK_WRAP_FAILED'&&!String(e.message).includes('provider')); await assert.rejects(kms.unwrapDek({keyVersion:'x',kmsKeyRef:'arn:aws:kms:ap-south-1:123456789012:key/33333333-3333-3333-3333-333333333333',wrappingAlgorithm:WRAPPING_ALGORITHM,wrappedDek:Buffer.from('x')}),e=>e.code==='DEK_UNWRAP_FAILED'); });
test('AWS KMS provider fails closed for malformed or provider-failed decrypt plaintext', async () => { const malformed=new AwsKmsProvider({client:client(()=>({Plaintext:Buffer.alloc(31)})),kmsKeyArn:ARN}); await assert.rejects(malformed.unwrapDek({keyVersion:'x',kmsKeyRef:ARN,wrappingAlgorithm:WRAPPING_ALGORITHM,wrappedDek:Buffer.from('x')}),e=>e.code==='DEK_UNWRAP_FAILED'); const failed=new AwsKmsProvider({client:client(()=>{throw new Error('synthetic AWS decrypt details');}),kmsKeyArn:ARN}); await assert.rejects(failed.unwrapDek({keyVersion:'x',kmsKeyRef:ARN,wrappingAlgorithm:WRAPPING_ALGORITHM,wrappedDek:Buffer.from('x')}),e=>e.code==='DEK_UNWRAP_FAILED'&&!String(e.message).includes('synthetic AWS')); });
test('AWS KMS startup validation accepts only enabled symmetric encrypt/decrypt keys', async () => { const good=new AwsKmsProvider({client:client(()=>({KeyMetadata:{Arn:ARN,KeyState:'Enabled',KeyUsage:'ENCRYPT_DECRYPT',KeySpec:'SYMMETRIC_DEFAULT'}})),kmsKeyArn:ARN}); assert.equal((await good.validateStartupKey()).keyArn,ARN); const bad=new AwsKmsProvider({client:client(()=>({KeyMetadata:{KeyState:'Disabled',KeyUsage:'SIGN_VERIFY',KeySpec:'RSA_2048'}})),kmsKeyArn:ARN}); await assert.rejects(bad.validateStartupKey(),e=>e.code==='KMS_STARTUP_VALIDATION_FAILED'); });
