'use strict';

const { freeze } = require('../synthesis/evidence-node');
const { requiredString, canonicalTime, immutableCopy, fail } = require('../persistence/contracts');

const PurchaseProvider = freeze(['APPLE', 'GOOGLE', 'WEB']);
const PurchaseEnvironment = freeze(['SANDBOX', 'PRODUCTION']);
const PurchaseStatus = freeze(['VERIFIED', 'PENDING', 'REVOKED', 'REFUNDED', 'FAILED']);
const SubscriptionStatus = freeze(['ACTIVE', 'GRACE_PERIOD', 'CANCELED', 'EXPIRED', 'REVOKED', 'REFUNDED']);
const PRODUCT_CATALOG = freeze([{ logicalSku: 'career_premium_annual', name: 'KundliInsights Career Premium', displayPrice: '₹599/year', scope: 'USER', kind: 'ANNUAL_SUBSCRIPTION', providerProductIds: freeze({ APPLE: null, GOOGLE: null, WEB: null }) }]);
function enumValue(value, values, code) { if (!values.includes(value)) fail(code); return value; }
function nullableString(value, code) { return value == null ? null : requiredString(value, code); }
function nullableTime(value, code) { return value == null ? null : canonicalTime(value, code); }
function requiredTime(value, code) { return canonicalTime(value, code); }
function timestamps(input) { const createdAt = requiredTime(input.createdAt, 'INVALID_PAYMENT_TIMESTAMP'); return { createdAt, updatedAt: input.updatedAt == null ? createdAt : requiredTime(input.updatedAt, 'INVALID_PAYMENT_TIMESTAMP') }; }
function purchaseRecord(input = {}) { const purchasedAt = requiredTime(input.purchasedAt, 'INVALID_PURCHASE_TIMESTAMP'); const validFrom = nullableTime(input.validFrom, 'INVALID_PURCHASE_VALIDITY'); const validUntil = nullableTime(input.validUntil, 'INVALID_PURCHASE_VALIDITY'); if (validFrom && validUntil && Date.parse(validUntil) <= Date.parse(validFrom)) fail('INVALID_PURCHASE_VALIDITY'); return immutableCopy({ id: requiredString(input.id, 'INVALID_PURCHASE_ID'), userId: requiredString(input.userId, 'INVALID_USER_ID'), provider: enumValue(input.provider, PurchaseProvider, 'INVALID_PURCHASE_PROVIDER'), environment: enumValue(input.environment, PurchaseEnvironment, 'INVALID_PURCHASE_ENVIRONMENT'), productId: requiredString(input.productId, 'INVALID_PRODUCT_ID'), providerTransactionId: requiredString(input.providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID'), originalTransactionId: nullableString(input.originalTransactionId, 'INVALID_ORIGINAL_TRANSACTION_ID'), status: enumValue(input.status, PurchaseStatus, 'INVALID_PURCHASE_STATUS'), purchasedAt, validFrom, validUntil, verifiedAt: requiredTime(input.verifiedAt, 'INVALID_PURCHASE_TIMESTAMP'), paymentTransactionId: nullableString(input.paymentTransactionId, 'INVALID_PAYMENT_TRANSACTION_ID'), ...timestamps(input) }); }
function subscriptionRecord(input = {}) { const validFrom = requiredTime(input.validFrom, 'INVALID_SUBSCRIPTION_VALIDITY'); const validUntil = requiredTime(input.validUntil, 'INVALID_SUBSCRIPTION_VALIDITY'); if (Date.parse(validUntil) <= Date.parse(validFrom)) fail('INVALID_SUBSCRIPTION_VALIDITY'); if (input.autoRenewEnabled != null && typeof input.autoRenewEnabled !== 'boolean') fail('INVALID_AUTO_RENEW_ENABLED'); return immutableCopy({ id: requiredString(input.id, 'INVALID_SUBSCRIPTION_ID'), userId: requiredString(input.userId, 'INVALID_USER_ID'), provider: enumValue(input.provider, PurchaseProvider, 'INVALID_PURCHASE_PROVIDER'), environment: enumValue(input.environment, PurchaseEnvironment, 'INVALID_PURCHASE_ENVIRONMENT'), productId: requiredString(input.productId, 'INVALID_PRODUCT_ID'), originalTransactionId: requiredString(input.originalTransactionId, 'INVALID_ORIGINAL_TRANSACTION_ID'), status: enumValue(input.status, SubscriptionStatus, 'INVALID_SUBSCRIPTION_STATUS'), validFrom, validUntil, autoRenewEnabled: input.autoRenewEnabled == null ? null : input.autoRenewEnabled, graceUntil: nullableTime(input.graceUntil, 'INVALID_SUBSCRIPTION_TIMESTAMP'), canceledAt: nullableTime(input.canceledAt, 'INVALID_SUBSCRIPTION_TIMESTAMP'), revokedAt: nullableTime(input.revokedAt, 'INVALID_SUBSCRIPTION_TIMESTAMP'), refundedAt: nullableTime(input.refundedAt, 'INVALID_SUBSCRIPTION_TIMESTAMP'), latestPurchaseRecordId: nullableString(input.latestPurchaseRecordId, 'INVALID_PURCHASE_ID'), providerEventTime: nullableTime(input.providerEventTime, 'INVALID_SUBSCRIPTION_TIMESTAMP'), providerEventVersion: nullableString(input.providerEventVersion, 'INVALID_PROVIDER_EVENT_VERSION'), ...timestamps(input) }); }
function paymentEvent(input = {}) { return immutableCopy({ id: requiredString(input.id, 'INVALID_PAYMENT_EVENT_ID'), provider: enumValue(input.provider, PurchaseProvider, 'INVALID_PURCHASE_PROVIDER'), environment: enumValue(input.environment, PurchaseEnvironment, 'INVALID_PURCHASE_ENVIRONMENT'), providerEventId: requiredString(input.providerEventId, 'INVALID_PROVIDER_EVENT_ID'), eventType: requiredString(input.eventType, 'INVALID_EVENT_TYPE'), providerEventTime: nullableTime(input.providerEventTime, 'INVALID_EVENT_TIMESTAMP'), purchaseRecordId: nullableString(input.purchaseRecordId, 'INVALID_PURCHASE_ID'), subscriptionRecordId: nullableString(input.subscriptionRecordId, 'INVALID_SUBSCRIPTION_ID'), receivedAt: requiredTime(input.receivedAt, 'INVALID_EVENT_TIMESTAMP'), processedAt: nullableTime(input.processedAt, 'INVALID_EVENT_TIMESTAMP'), processingStatus: enumValue(input.processingStatus, ['RECEIVED', 'PROCESSED', 'FAILED'], 'INVALID_EVENT_STATUS'), failureCode: nullableString(input.failureCode, 'INVALID_EVENT_FAILURE_CODE'), payloadDigest: input.payloadDigest == null ? null : (/^[0-9a-f]{64}$/.test(input.payloadDigest) ? input.payloadDigest : fail('INVALID_EVENT_PAYLOAD_DIGEST')), ...timestamps(input) }); }
function getProduct(logicalSku) { const product = PRODUCT_CATALOG.find((value) => value.logicalSku === logicalSku); if (!product) fail('UNKNOWN_PRODUCT_SKU'); return product; }
function getProductByProviderProductId(provider, providerProductId) { enumValue(provider, PurchaseProvider, 'INVALID_PURCHASE_PROVIDER'); const product = PRODUCT_CATALOG.find((value) => value.providerProductIds[provider] === providerProductId); return product || null; }
const PurchaseVerifierContract = freeze({ verify: 'verify({ provider, environment, evidence, authenticatedUser }) => normalized verified purchase' });
const SubscriptionReconcilerContract = freeze({ reconcile: 'reconcile({ verifiedPurchase, existingSubscription, event }) => normalized subscription state' });
module.exports = { PurchaseProvider, PurchaseEnvironment, PurchaseStatus, SubscriptionStatus, PRODUCT_CATALOG, getProduct, getProductByProviderProductId, purchaseRecord, subscriptionRecord, paymentEvent, PurchaseVerifierContract, SubscriptionReconcilerContract };
