'use strict';
const { PostgresPurchaseRepository, PostgresSubscriptionRepository, PostgresProfileEntitlementRepository, PostgresProviderPaymentOrderRepository } = require('../persistence');
class PostgresPaymentUnitOfWork {
  constructor({ pool, birthProfileRepositoryFactory = null } = {}) { if (!pool || typeof pool.connect !== 'function') throw new TypeError('INVALID_PAYMENT_POOL'); this.pool = pool; this.birthProfileRepositoryFactory = birthProfileRepositoryFactory; }
  async run(callback) { const client = await this.pool.connect(); let begun = false; try { await client.query('BEGIN'); begun = true; const value = await callback({ purchases: new PostgresPurchaseRepository({ db: client }), subscriptions: new PostgresSubscriptionRepository({ db: client }), profileEntitlements: new PostgresProfileEntitlementRepository({ db: client }), providerPaymentOrders: new PostgresProviderPaymentOrderRepository({ db: client }), birthProfiles: this.birthProfileRepositoryFactory ? this.birthProfileRepositoryFactory(client) : null }); await client.query('COMMIT'); return value; } catch (error) { if (begun) try { await client.query('ROLLBACK'); } catch {} throw error; } finally { client.release(); } }
}
class InMemoryPaymentUnitOfWork {
  constructor({ repositories } = {}) { this.repositories = repositories; }
  async run(callback) { const source = this.repositories(); const clone = (value) => Object.assign(Object.create(Object.getPrototypeOf(value)), value); const purchases = clone(source.purchases); purchases.records = new Map(source.purchases.records); purchases.byProviderTransaction = new Map(source.purchases.byProviderTransaction); const subscriptions = clone(source.subscriptions); subscriptions.records = new Map(source.subscriptions.records); subscriptions.byIdentity = new Map(source.subscriptions.byIdentity); const profileEntitlements = source.profileEntitlements ? clone(source.profileEntitlements) : null; if (profileEntitlements) { profileEntitlements.records = new Map(source.profileEntitlements.records); profileEntitlements.byProfile = new Map(source.profileEntitlements.byProfile); profileEntitlements.byPurchase = new Map(source.profileEntitlements.byPurchase); } const providerPaymentOrders = source.providerPaymentOrders ? clone(source.providerPaymentOrders) : null; if (providerPaymentOrders) { providerPaymentOrders.records = new Map(source.providerPaymentOrders.records); providerPaymentOrders.byProviderOrder = new Map(source.providerPaymentOrders.byProviderOrder); providerPaymentOrders.byProviderPayment = new Map(source.providerPaymentOrders.byProviderPayment); } const value = await callback({ purchases, subscriptions, profileEntitlements, providerPaymentOrders, birthProfiles: source.birthProfiles || null }); source.purchases.records = purchases.records; source.purchases.byProviderTransaction = purchases.byProviderTransaction; source.subscriptions.records = subscriptions.records; source.subscriptions.byIdentity = subscriptions.byIdentity; if (profileEntitlements) { source.profileEntitlements.records = profileEntitlements.records; source.profileEntitlements.byProfile = profileEntitlements.byProfile; source.profileEntitlements.byPurchase = profileEntitlements.byPurchase; } if (providerPaymentOrders) { source.providerPaymentOrders.records = providerPaymentOrders.records; source.providerPaymentOrders.byProviderOrder = providerPaymentOrders.byProviderOrder; source.providerPaymentOrders.byProviderPayment = providerPaymentOrders.byProviderPayment; } return value; }
}
module.exports = { PostgresPaymentUnitOfWork, InMemoryPaymentUnitOfWork };
