'use strict';

const { DEFAULT_ALGORITHMS } = require('../security/auth/supabase-auth-verifier');

function invalid() { const error = new Error('Invalid development configuration.'); error.code = 'INVALID_DEVELOPMENT_CONFIGURATION'; throw error; }
function text(value) { return typeof value === 'string' && value.trim() === value && value.length > 0; }
function integer(value, fallback, minimum, maximum) { const raw = value === undefined ? fallback : value; if (!/^(0|[1-9]\d*)$/.test(String(raw))) invalid(); const result = Number(raw); if (!Number.isSafeInteger(result) || result < minimum || result > maximum) invalid(); return result; }
function databaseUrl(value) { if (!text(value)) invalid(); try { const parsed = new URL(value); if (!['postgres:', 'postgresql:'].includes(parsed.protocol) || !parsed.hostname) invalid(); return value; } catch { invalid(); } }
function httpsUrl(value) { if (!text(value)) invalid(); try { const parsed = new URL(value); if (parsed.protocol !== 'https:') invalid(); return parsed.toString(); } catch { invalid(); } }
function localKey(value) { if (!text(value)) invalid(); const key = Buffer.from(value, 'base64'); if (key.length !== 32 || key.toString('base64') !== value) invalid(); return key; }
function placeResolver(env) { const values = [env.GOOGLE_MAPS_API_KEY, env.TIMEZONE_RUNTIME_MANIFEST_PATH, env.TIMEZONE_RUNTIME_BINARY_PATH]; if (values.every((value) => value === undefined || value === '')) return null; if (!values.every(text)) invalid(); return Object.freeze({ googleMapsApiKey: env.GOOGLE_MAPS_API_KEY, timeoutMilliseconds: integer(env.GOOGLE_GEOCODING_TIMEOUT_MS, 5000, 100, 15000), manifestPath: env.TIMEZONE_RUNTIME_MANIFEST_PATH, binaryPath: env.TIMEZONE_RUNTIME_BINARY_PATH }); }
function googlePlay(env) { const productIds = [env.GOOGLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID, env.GOOGLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID]; const values = [env.GOOGLE_PACKAGE_NAME, env.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON]; if (values.concat(productIds).every((value) => value === undefined || value === '')) return null; if (!values.every(text) || !productIds.some(text) || !productIds.every((value) => value === undefined || value === '' || text(value))) invalid(); try { const rtdnValues = [env.GOOGLE_RTDN_AUDIENCE, env.GOOGLE_RTDN_ALLOWED_SERVICE_ACCOUNT_EMAIL]; if (!rtdnValues.every((value) => value === undefined || value === '') && (!rtdnValues.every(text) || !text(env.GOOGLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID))) invalid(); return Object.freeze({ packageName: env.GOOGLE_PACKAGE_NAME, careerPremiumAnnualProductId: text(env.GOOGLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID) ? env.GOOGLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID : null, careerProfileUnlockProductId: text(env.GOOGLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID) ? env.GOOGLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID : null, serviceAccount: JSON.parse(env.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON), rtdn: rtdnValues.every(text) ? Object.freeze({ audience: env.GOOGLE_RTDN_AUDIENCE, allowedServiceAccountEmail: env.GOOGLE_RTDN_ALLOWED_SERVICE_ACCOUNT_EMAIL }) : null }); } catch { invalid(); } }
function razorpay(env) { const values = [env.RAZORPAY_KEY_ID, env.RAZORPAY_KEY_SECRET, env.RAZORPAY_WEBHOOK_SECRET, env.RAZORPAY_PRODUCT_CATALOG_JSON]; if (values.every((value) => value === undefined || value === '')) return null; if (!values.every(text)) invalid(); try { const products = JSON.parse(env.RAZORPAY_PRODUCT_CATALOG_JSON); if (!Array.isArray(products)) invalid(); return Object.freeze({ keyId: env.RAZORPAY_KEY_ID, keySecret: env.RAZORPAY_KEY_SECRET, webhookSecret: env.RAZORPAY_WEBHOOK_SECRET, products }); } catch { invalid(); } }
function careerChat(env) { if (env.CAREER_CHAT_LLM_ENABLED !== 'true') return Object.freeze({ enabled: false }); if (!text(env.CAREER_CHAT_OPENAI_API_KEY) || !text(env.CAREER_CHAT_OPENAI_MODEL)) invalid(); return Object.freeze({ enabled: true, apiKey: env.CAREER_CHAT_OPENAI_API_KEY, model: env.CAREER_CHAT_OPENAI_MODEL, timeoutMilliseconds: integer(env.CAREER_CHAT_LLM_TIMEOUT_MS, 8000, 100, 15000) }); }

function loadDevelopmentConfig(env = process.env) {
  if (!env || env.NODE_ENV !== 'development') invalid(); const algorithms = text(env.DEV_SUPABASE_AUTH_ALLOWED_ALGORITHMS) ? env.DEV_SUPABASE_AUTH_ALLOWED_ALGORITHMS.split(',') : DEFAULT_ALGORITHMS;
  if (!algorithms.length || !algorithms.every((algorithm) => DEFAULT_ALGORITHMS.includes(algorithm))) invalid();
  return Object.freeze({ host: text(env.DEV_HOST) ? env.DEV_HOST : '0.0.0.0', port: integer(env.DEV_PORT, 3000, 1, 65535), databaseUrl: databaseUrl(env.DEV_DATABASE_URL), placeResolver: placeResolver(env), googlePlay: googlePlay(env), razorpay: razorpay(env), careerChat: careerChat(env), apple: Object.freeze({ bundleId: text(env.APPLE_BUNDLE_ID) ? env.APPLE_BUNDLE_ID : null, careerPremiumAnnualProductId: text(env.APPLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID) ? env.APPLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID : null }), auth: Object.freeze({ issuer: httpsUrl(env.DEV_SUPABASE_AUTH_ISSUER), jwksUri: httpsUrl(env.DEV_SUPABASE_AUTH_JWKS_URL), audience: text(env.DEV_SUPABASE_AUTH_AUDIENCE) ? env.DEV_SUPABASE_AUTH_AUDIENCE : invalid(), allowedAlgorithms: Object.freeze([...new Set(algorithms)]) }), localKms: Object.freeze({ key: localKey(env.DEV_LOCAL_KMS_KEY_BASE64), keyVersion: text(env.DEV_LOCAL_KMS_KEY_VERSION) ? env.DEV_LOCAL_KMS_KEY_VERSION : 'development-local-kek-v1' }), corsOrigins: Object.freeze([]), bodyLimitBytes: integer(env.DEV_REQUEST_BODY_LIMIT_BYTES, 16384, 1024, 16384) });
}

module.exports = { loadDevelopmentConfig };
