'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createApi}=require('../../src/api');const {AshtakavargaService}=require('../../src/application/ashtakavarga');const {calculateRawAshtakavarga}=require('../../src/ashtakavarga');const {createTestOnlyAuthVerifier}=require('../../src/api/test-only-auth-verifier');
const a={provider:'supabase',subject:'a',isAnonymous:false},b={provider:'supabase',subject:'b',isAnonymous:false};const names=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu','Ascendant'];const lons=Object.fromEntries(names.map((n,i)=>[n,i*30+1]));
const birthData={localDate:'1990-01-01',localTime:'00:00:00',timezone:'UTC',latitude:0,longitude:0};
function engine(){return {calculate(){return {bodies:Object.fromEntries(names.map(n=>[n,{body:n,siderealLongitudeDegrees:lons[n],motion:'direct'}]))}}};}
function profiles(){return {async get({principal,birthProfileId}){if(principal.subject!=='a'||birthProfileId!=='p'){const e=new Error();e.code='NOT_FOUND_OR_FORBIDDEN';throw e;}return {id:'p',status:'active',birthData};}};}
function app(){return createApi({authVerifier:createTestOnlyAuthVerifier({a,b}),userResolver:{resolve:async()=>({id:'u',status:'active'})},birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>null},ashtakavargaService:new AshtakavargaService({birthProfileService:profiles(),astronomicalEngine:engine()}),secureReadingService:{},requestIdGenerator:()=> 'r'});}
function safe(x){const s=JSON.stringify(x).toLowerCase();for(const k of ['birthdata','ciphertext','dek','kms','subject','contributor','shodhana','pinda','prediction','interpretation','favorable','house'])assert.equal(s.includes(k),false,k);}
test('owned API-P5B response exposes authoritative raw SAV, seven BAVs, and separate Lagna BAV only',async()=>{const api=app(),r=await api.inject({url:'/v1/birth-profiles/p/ashtakavarga',headers:{authorization:'Bearer a'}});assert.equal(r.statusCode,200);const x=r.json().ashtakavarga;const raw=calculateRawAshtakavarga({rashiPlacements:{Sun:1,Moon:2,Mars:3,Mercury:4,Jupiter:5,Venus:6,Saturn:7,Ascendant:10}});assert.equal(x.sav.signScores.length,12);assert.equal(new Set(x.sav.signScores.map(v=>v.sign.rashiIndex)).size,12);assert.deepEqual(x.sav.signScores.map(v=>v.score),raw.rawSarvashtakavarga.rashis.map(v=>v.favorableMarkCount));assert.deepEqual(x.bav.map(v=>v.body),['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn']);for(const bav of x.bav){assert.equal(bav.signScores.length,12);assert.deepEqual(bav.signScores.map(v=>v.score),raw.planetaryBavs[bav.body].rashis.map(v=>v.favorableMarkCount));}assert.equal(x.lagnaBav.signScores.length,12);assert.deepEqual(x.lagnaBav.signScores.map(v=>v.score),raw.lagnaBav.rashis.map(v=>v.favorableMarkCount));safe(r.json());await api.close();});
test('API-P5B requires auth and safely denies foreign profiles',async()=>{const api=app();assert.equal((await api.inject('/v1/birth-profiles/p/ashtakavarga')).statusCode,401);const r=await api.inject({url:'/v1/birth-profiles/p/ashtakavarga',headers:{authorization:'Bearer b'}});assert.equal(r.statusCode,404);safe(r.json());await api.close();});
