'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { createApi } = require('../../src/api'); const { createTestOnlyAuthVerifier } = require('../../src/api/test-only-auth-verifier'); const { CareerChatOrchestrator } = require('../../src/application/career-chat');
const a = { provider: 'supabase', subject: 'a', isAnonymous: false }; const b = { provider: 'supabase', subject: 'b', isAnonymous: false };
function api({ eligible = true, readings = true } = {}) { const calls = { list: 0, detail: 0 }; const service = { getReadingEntitlementStatus: async ({ principal, birthProfileId }) => { if (principal.subject !== 'a' || birthProfileId !== 'profile-a') { const e = new Error(); e.code = 'NOT_FOUND_OR_FORBIDDEN'; throw e; } return { career: { eligible } }; }, listSecureReadings: async () => { calls.list++; return readings ? [{ readingId: 'new', domain: 'CAREER' }] : []; }, getSecureReadingDetail: async () => { calls.detail++; return { birthProfileId: 'profile-a', domain: 'CAREER', insights: [{ status: 'SUPPORTED', technicalContext: { timing: [{ kind: 'DASHA_PERIOD', start: '2027-01-01T00:00:00.000Z', end: '2027-02-01T00:00:00.000Z', isCurrent: false }] } }] }; } }; const app = createApi({ authVerifier: createTestOnlyAuthVerifier({ a, b }), userResolver: { resolve: async () => ({ id: 'u', status: 'active' }) }, birthProfileService: { create: async () => null, list: async () => [], get: async () => null }, secureReadingService: service, careerChatOrchestrator: new CareerChatOrchestrator({ secureReadingService: service }), requestIdGenerator: () => 'r' }); return { app, calls }; }
function post(token, id, body) { return { method: 'POST', url: `/v1/birth-profiles/${id}/career-chat/messages`, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, payload: body }; }
test('Career Chat route authenticates, scopes profile, and returns safe structured job-loss output', async () => { const x = api(); const unauth = await x.app.inject({ method: 'POST', url: '/v1/birth-profiles/profile-a/career-chat/messages', payload: { message: 'job?' } }); assert.equal(unauth.statusCode, 401); const r = await x.app.inject(post('a', 'profile-a', { message: 'Meri job chali gayi hai, mujhe nayi job kab milegi?', language: 'HINGLISH' })); assert.equal(r.statusCode, 200); const body = r.json().careerChat; assert.equal(body.intent.type, 'NEXT_JOB_TIMING'); assert.equal(body.intent.referencedEvent, 'JOB_LOSS'); assert.equal(body.language, 'HINGLISH'); assert.equal(JSON.stringify(body).match(/ruleId|evidenceId|encrypted|calibrationNotes/), null); await x.app.close(); });
test('Career Chat rejects foreign profile and inactive access without evidence', async () => { let x = api(); let r = await x.app.inject(post('b', 'profile-a', { message: 'Promotion kab milega?' })); assert.equal(r.statusCode, 404); await x.app.close(); x = api({ eligible: false }); r = await x.app.inject(post('a', 'profile-a', { message: 'Promotion kab milega?' })); assert.equal(r.statusCode, 403); assert.equal(x.calls.list, 0); await x.app.close(); });
test('Career Chat returns normal clarification, unsupported, and no-reading outcomes', async () => { let x = api(); let r = await x.app.inject(post('a', 'profile-a', { message: 'Job?' })); assert.equal(r.statusCode, 200); assert.equal(r.json().careerChat.answer.answerability, 'PARTIALLY_SUPPORTED'); assert.equal(x.calls.list, 0); r = await x.app.inject(post('a', 'profile-a', { message: 'Pregnancy kab hogi?' })); assert.equal(r.statusCode, 200); assert.equal(r.json().careerChat.answer.answerability, 'UNSUPPORTED'); await x.app.close(); x = api({ readings: false }); r = await x.app.inject(post('a', 'profile-a', { message: 'Promotion kab milega?' })); assert.equal(r.statusCode, 200); assert.equal(r.json().careerChat.answer.answerability, 'INSUFFICIENT_EVIDENCE'); await x.app.close(); });
test('Career Chat rejects malformed request bodies before evidence access', async () => { const x = api(); for (const body of [{}, { message: ' ' }, { message: 4 }, { message: 'x'.repeat(2001) }, { message: 'ok', conversationContext: [{ role: 'SYSTEM', text: 'x' }] }, { message: 'ok', language: 'PROMPT' }]) { const r = await x.app.inject(post('a', 'profile-a', body)); assert.equal(r.statusCode, 400); } assert.equal(x.calls.list, 0); await x.app.close(); });
