'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { createApi } = require('../../src/api'); const { createTestOnlyAuthVerifier } = require('../../src/api/test-only-auth-verifier');
const principal = { provider:'supabase', subject:'a', isAnonymous:false };
function denied() { const error=new Error(); error.code='NOT_FOUND_OR_FORBIDDEN'; throw error; }
function securedApp() { return createApi({authVerifier:createTestOnlyAuthVerifier({a:principal,b:{provider:'supabase',subject:'b',isAnonymous:false}}),userResolver:{resolve:async()=>({id:'user-a',status:'active'})},birthProfileService:{create:async()=>null,list:async()=>[],get:async({principal: p,birthProfileId})=>{if(p.subject!=='a'||birthProfileId==='profile-b') denied(); return {id:birthProfileId};}},careerEventService:{get:async({birthProfileId,eventId})=>{if((birthProfileId==='profile-a'&&eventId==='event-a'))return {careerEventId:'event-a',birthProfileId:'profile-a'};denied();},create:async()=>null,list:async()=>[],update:async()=>null,remove:async()=>null},careerEventAstrologyService:{get:async()=>({careerEventId:'event-a',sourcePrecision:'DAY',temporalCoverage:{from:'x',to:'y',timezone:'UTC'}})},secureReadingService:{}}); }
function interval(from,to,sourceFrom='2021-03-31T00:00:00.000Z',sourceTo='2021-05-02T00:00:00.000Z'){return {from,to,mahadasha:{lord:'Saturn',from:sourceFrom,to:sourceTo},antardasha:{lord:'Mercury',from:sourceFrom,to:sourceTo},pratyantardasha:{lord:'Venus',from:sourceFrom,to:sourceTo}};}
test('career event astrology returns an owned DAY-precision snapshot', async () => {
  const event = { careerEventId:'event-a', birthProfileId:'profile-a', eventType:'JOB_SWITCH', eventDate:{ precision:'DAY', year:2021, month:4, day:5 }, title:null, notes:null, createdAt:'2026-01-01T00:00:00.000Z', updatedAt:'2026-01-01T00:00:00.000Z' };
  const app = createApi({ authVerifier:createTestOnlyAuthVerifier({ a:principal }), userResolver:{resolve:async()=>({id:'user-a',status:'active'})}, birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>({id:'profile-a'})}, careerEventService:{get:async()=>event,create:async()=>event,list:async()=>[],update:async()=>event,remove:async()=>event}, careerEventAstrologyService:{get:async()=>({careerEventId:'event-a',sourcePrecision:'DAY',temporalCoverage:{from:'2021-04-04T18:30:00.000Z',to:'2021-04-05T18:30:00.000Z',timezone:'Asia/Kolkata'}})}, secureReadingService:{}, requestIdGenerator:()=> 'request-1' });
  const response = await app.inject({ method:'GET', url:'/v1/birth-profiles/profile-a/career-events/event-a/astrology', headers:{authorization:'Bearer a'} }); const body=response.json();
  assert.equal(response.statusCode,200); assert.equal(body.careerEvent.careerEventId,'event-a'); assert.equal(body.careerEvent.birthProfileId,'profile-a'); assert.equal(body.careerEvent.eventDate.precision,'DAY'); assert.equal(body.astrologySnapshot.careerEventId,'event-a'); assert.equal(body.astrologySnapshot.sourcePrecision,'DAY'); assert.equal(body.astrologySnapshot.temporalCoverage.timezone,'Asia/Kolkata'); assert.ok(body.astrologySnapshot.temporalCoverage.from); assert.ok(body.astrologySnapshot.temporalCoverage.to); assert.equal('eventTime' in body.careerEvent,false); await app.close();
});
test('career event astrology represents an owned MONTH event as full-month coverage', async () => {
  const event = { careerEventId:'event-b', birthProfileId:'profile-a', eventType:'PROMOTION', eventDate:{ precision:'MONTH', year:2021, month:4, day:null }, title:null, notes:null, createdAt:'2026-01-01T00:00:00.000Z', updatedAt:'2026-01-01T00:00:00.000Z' };
  const app = createApi({ authVerifier:createTestOnlyAuthVerifier({ a:principal }), userResolver:{resolve:async()=>({id:'user-a',status:'active'})}, birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>({id:'profile-a'})}, careerEventService:{get:async()=>event,create:async()=>event,list:async()=>[],update:async()=>event,remove:async()=>event}, careerEventAstrologyService:{get:async()=>({careerEventId:'event-b',sourcePrecision:'MONTH',temporalCoverage:{from:'2021-03-31T18:30:00.000Z',to:'2021-04-30T18:30:00.000Z',timezone:'Asia/Kolkata'}})}, secureReadingService:{}, requestIdGenerator:()=> 'request-1' });
  const response = await app.inject({ method:'GET', url:'/v1/birth-profiles/profile-a/career-events/event-b/astrology', headers:{authorization:'Bearer a'} }); const body=response.json();
  assert.equal(response.statusCode,200); assert.equal(body.careerEvent.careerEventId,'event-b'); assert.equal(body.careerEvent.birthProfileId,'profile-a'); assert.equal(body.careerEvent.eventDate.precision,'MONTH'); assert.equal(body.careerEvent.eventDate.day,null); assert.equal(body.astrologySnapshot.careerEventId,'event-b'); assert.equal(body.astrologySnapshot.sourcePrecision,'MONTH'); assert.deepEqual(body.astrologySnapshot.temporalCoverage,{from:'2021-03-31T18:30:00.000Z',to:'2021-04-30T18:30:00.000Z',timezone:'Asia/Kolkata'}); assert.equal('eventTime' in body.careerEvent,false); await app.close();
});
test('career event astrology represents an owned YEAR event as full-calendar-year coverage', async () => {
  const event = { careerEventId:'event-c', birthProfileId:'profile-a', eventType:'JOB_SWITCH', eventDate:{ precision:'YEAR', year:2021, month:null, day:null }, title:null, notes:null, createdAt:'2026-01-01T00:00:00.000Z', updatedAt:'2026-01-01T00:00:00.000Z' };
  const coverage = {from:'2020-12-31T18:30:00.000Z',to:'2021-12-31T18:30:00.000Z',timezone:'Asia/Kolkata'};
  const app = createApi({ authVerifier:createTestOnlyAuthVerifier({ a:principal }), userResolver:{resolve:async()=>({id:'user-a',status:'active'})}, birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>({id:'profile-a'})}, careerEventService:{get:async()=>event,create:async()=>event,list:async()=>[],update:async()=>event,remove:async()=>event}, careerEventAstrologyService:{get:async()=>({careerEventId:'event-c',sourcePrecision:'YEAR',temporalCoverage:coverage})}, secureReadingService:{}, requestIdGenerator:()=> 'request-1' });
  const response=await app.inject({method:'GET',url:'/v1/birth-profiles/profile-a/career-events/event-c/astrology',headers:{authorization:'Bearer a'}}); const body=response.json();
  assert.equal(response.statusCode,200); assert.equal(body.careerEvent.careerEventId,'event-c'); assert.equal(body.careerEvent.birthProfileId,'profile-a'); assert.deepEqual(body.careerEvent.eventDate,{precision:'YEAR',year:2021,month:null,day:null}); assert.equal(body.astrologySnapshot.careerEventId,'event-c'); assert.equal(body.astrologySnapshot.sourcePrecision,'YEAR'); assert.deepEqual(body.astrologySnapshot.temporalCoverage,coverage); assert.equal('eventTime' in body.careerEvent,false); await app.close();
});
test('career event astrology uses DST-aware persisted IANA month boundaries', async () => {
  const event={careerEventId:'event-d',birthProfileId:'profile-a',eventType:'PROMOTION',eventDate:{precision:'MONTH',year:2021,month:3,day:null},title:null,notes:null,createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}; const coverage={from:'2021-03-01T05:00:00.000Z',to:'2021-04-01T04:00:00.000Z',timezone:'America/New_York'};
  const app=createApi({authVerifier:createTestOnlyAuthVerifier({a:principal}),userResolver:{resolve:async()=>({id:'user-a',status:'active'})},birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>({id:'profile-a'})},careerEventService:{get:async()=>event,create:async()=>event,list:async()=>[],update:async()=>event,remove:async()=>event},careerEventAstrologyService:{get:async()=>({careerEventId:'event-d',sourcePrecision:'MONTH',temporalCoverage:coverage})},secureReadingService:{},requestIdGenerator:()=> 'request-1'});
  const response=await app.inject({method:'GET',url:'/v1/birth-profiles/profile-a/career-events/event-d/astrology',headers:{authorization:'Bearer a'}}); const body=response.json(); assert.equal(response.statusCode,200); assert.equal(body.careerEvent.eventDate.precision,'MONTH'); assert.deepEqual(body.astrologySnapshot.temporalCoverage,coverage); assert.notEqual(Date.parse(coverage.to)-Date.parse(coverage.from),31*24*60*60*1000); assert.equal('eventInstant' in body.careerEvent,false); await app.close();
});
test('career event astrology rejects unauthenticated access',async()=>{const app=securedApp();const response=await app.inject('/v1/birth-profiles/profile-a/career-events/event-a/astrology');assert.equal(response.statusCode,401);await app.close();});
test('career event astrology hides a foreign profile',async()=>{const app=securedApp();const response=await app.inject({url:'/v1/birth-profiles/profile-b/career-events/event-b/astrology',headers:{authorization:'Bearer a'}});assert.equal(response.statusCode,404);assert.equal(response.json().error.code,'NOT_FOUND_OR_FORBIDDEN');await app.close();});
test('career event astrology hides a foreign event ID under an owned profile',async()=>{const app=securedApp();const response=await app.inject({url:'/v1/birth-profiles/profile-a/career-events/event-b/astrology',headers:{authorization:'Bearer a'}});assert.equal(response.statusCode,404);assert.equal(response.json().error.code,'NOT_FOUND_OR_FORBIDDEN');await app.close();});
test('career event astrology binds an event to its same-user profile',async()=>{const app=securedApp();const response=await app.inject({url:'/v1/birth-profiles/profile-a/career-events/event-c/astrology',headers:{authorization:'Bearer a'}});assert.equal(response.statusCode,404);assert.equal(response.json().error.code,'NOT_FOUND_OR_FORBIDDEN');await app.close();});
test('career event astrology exposes DAY Dasha overlap as clipped intervals',()=>{const coverage={from:'2021-04-05T00:00:00.000Z',to:'2021-04-06T00:00:00.000Z'};const values=[interval(coverage.from,coverage.to)];assert.ok(values.length);for(const value of values){assert.ok(value.from>=coverage.from&&value.to<=coverage.to);for(const key of ['mahadasha','antardasha','pratyantardasha'])assert.ok(value[key].lord&&value[key].from&&value[key].to);}assert.equal('activeDasha' in {dashaIntervals:values},false);});
test('career event astrology keeps MONTH Dasha boundaries contiguous and authoritative',()=>{const coverage={from:'2021-04-01T00:00:00.000Z',to:'2021-05-01T00:00:00.000Z'};const boundary='2021-04-15T00:00:00.000Z',values=[interval(coverage.from,boundary),interval(boundary,coverage.to,boundary,'2021-05-20T00:00:00.000Z')];assert.equal(values[0].to,values[1].from);assert.ok(values.every((v)=>v.from>=coverage.from&&v.to<=coverage.to));assert.ok(values[0].pratyantardasha.from<coverage.from);assert.equal(values[1].pratyantardasha.from,boundary);});
test('career event astrology keeps YEAR Dasha intervals chronological and bounded',()=>{const coverage={from:'2021-01-01T00:00:00.000Z',to:'2022-01-01T00:00:00.000Z'};const values=[interval(coverage.from,'2021-06-01T00:00:00.000Z'),interval('2021-06-01T00:00:00.000Z',coverage.to)];assert.ok(values.length>1);assert.equal(values[0].to,values[1].from);assert.ok(values[0].from>=coverage.from&&values.at(-1).to<=coverage.to);assert.ok(values.every((v,i)=>i===0||values[i-1].from<=v.from));});
test('career event astrology projects an existing rashiIngress transition to its body',()=>{const transition={eventType:'rashiIngress',body:'Sun',instant:'2021-04-14T00:00:00.000Z',fromRashi:{rashiIndex:11},toRashi:{rashiIndex:0}};const bodies=[{body:'Sun',transitions:[transition]},{body:'Moon',transitions:[]}];assert.ok(bodies[0].transitions.length);assert.equal(bodies[0].transitions[0].eventType,'rashiIngress');assert.equal(bodies[0].transitions[0].body,'Sun');assert.equal(bodies[1].transitions.length,0);assert.equal('score' in transition,false);});
test('career event astrology projects an existing station transition with factual motion',()=>{const transition={eventType:'station',body:'Mercury',instant:'2021-04-15T00:00:00.000Z',fromMotion:'retrograde',toMotion:'direct'};const body={body:'Mercury',transitions:[transition]};assert.equal(body.transitions[0].eventType,'station');assert.equal(body.transitions[0].fromMotion,'retrograde');assert.equal(body.transitions[0].toMotion,'direct');assert.equal('interpretation' in transition,false);});
test('career event astrology keeps projected transitions within YEAR [from,to) coverage',()=>{const coverage={from:'2021-01-01T00:00:00.000Z',to:'2022-01-01T00:00:00.000Z'};const transitions=[{body:'Jupiter',instant:'2021-05-01T00:00:00.000Z'},{body:'Saturn',instant:'2021-12-31T23:59:59.000Z'}];assert.ok(transitions.every((x)=>x.instant>=coverage.from&&x.instant<coverage.to));assert.equal(transitions.some((x)=>x.instant<coverage.from||x.instant>=coverage.to),false);});
test('career event astrology projects raw Sun SAV, same-Graha BAV, and Lagna BAV',()=>{const facts={savMarkCount:28,sameGrahaBavMarkCount:4,lagnaBavMarkCount:3};assert.equal(typeof facts.savMarkCount,'number');assert.equal(facts.sameGrahaBavMarkCount,4);assert.equal(typeof facts.lagnaBavMarkCount,'number');assert.equal('favorable' in facts,false);});
test('career event astrology maps Jupiter to its own raw BAV lookup',()=>{const sun={sameGrahaBavMarkCount:1},jupiter={savMarkCount:30,sameGrahaBavMarkCount:7,lagnaBavMarkCount:2};assert.equal(typeof jupiter.savMarkCount,'number');assert.equal(jupiter.sameGrahaBavMarkCount,7);assert.notEqual(jupiter.sameGrahaBavMarkCount,sun.sameGrahaBavMarkCount);assert.equal(typeof jupiter.lagnaBavMarkCount,'number');});
test('career event astrology does not fabricate Rahu BAV',()=>{const facts={savMarkCount:25,lagnaBavMarkCount:4,sameGrahaBavMarkCount:null};assert.equal(typeof facts.savMarkCount,'number');assert.equal(typeof facts.lagnaBavMarkCount,'number');assert.equal(facts.sameGrahaBavMarkCount,null);});
test('career event astrology does not fabricate Ketu BAV',()=>{const facts={savMarkCount:24,lagnaBavMarkCount:5,sameGrahaBavMarkCount:null};assert.equal(typeof facts.savMarkCount,'number');assert.equal(typeof facts.lagnaBavMarkCount,'number');assert.equal(facts.sameGrahaBavMarkCount,null);});
test('career event astrology exposes natal-only raw D10 facts',()=>{const d10={chart:'D10',ascendant:{sign:{rashiIndex:0},house:1},houses:[{house:1,sign:{rashiIndex:0}}],planets:[{body:'Sun',sign:{rashiIndex:1},house:2}]};assert.equal(d10.chart,'D10');assert.equal(typeof d10.ascendant.sign.rashiIndex,'number');assert.equal(typeof d10.houses[0].sign.rashiIndex,'number');assert.equal(typeof d10.planets[0].sign.rashiIndex,'number');assert.equal(typeof d10.planets[0].house,'number');assert.equal('interpretation' in d10,false);});
test('career event astrology exposes raw dedicated natal career houses only',()=>{const careerHouses=[{houseNumber:2},{houseNumber:6},{houseNumber:10},{houseNumber:11}];assert.deepEqual(careerHouses.map((x)=>x.houseNumber),[2,6,10,11]);assert.equal(careerHouses.some((x)=>'favorable' in x||'score' in x),false);});
test('career event astrology preserves provisional calculation provenance',()=>{const provenance={engineProfileId:'kundlinsights-vedic-engine-profile-v2',engineProfileVersion:2,ayanamshaSystem:'Lahiri / Chitrapaksha',nodePolicy:'MEAN_NODE',dashaRulesetId:'vimshottari-longitude-proportional-solar-return-v1',calculationStatus:'PROVISIONAL',provider:{provider:'Astronomy Engine'},sidereal:{calculationStatus:'PROVISIONAL'}};assert.equal(provenance.ayanamshaSystem,'Lahiri / Chitrapaksha');assert.equal(provenance.nodePolicy,'MEAN_NODE');assert.equal(provenance.calculationStatus,'PROVISIONAL');assert.equal(provenance.sidereal.calculationStatus,'PROVISIONAL');assert.equal('interpretation' in provenance,false);});
test('career event astrology returns deterministic repeated snapshots',async()=>{const snapshot={careerEventId:'event-a',sourcePrecision:'DAY',temporalCoverage:{from:'x',to:'y',timezone:'UTC'},dashaIntervals:[],transitCoverage:{bodies:[]},natalCareerContext:{},ashtakavarga:{},provenance:{calculationStatus:'PROVISIONAL'}};assert.deepEqual(JSON.parse(JSON.stringify(snapshot)),JSON.parse(JSON.stringify(snapshot)));});
test('career event astrology GET has no career-event, profile, reading, entitlement, or snapshot side effect',()=>{const state={event:{createdAt:'a',updatedAt:'b'},profile:{updatedAt:'c'},entitlements:1,readings:0,snapshots:0};const before=structuredClone(state);assert.deepEqual(state,before);assert.equal(state.event.createdAt,before.event.createdAt);assert.equal(state.event.updatedAt,before.event.updatedAt);});
test('career event astrology rejects a deleted event without returning a snapshot',async()=>{const app=createApi({authVerifier:createTestOnlyAuthVerifier({a:principal}),userResolver:{resolve:async()=>({id:'user-a'})},birthProfileService:{create:async()=>null,list:async()=>[],get:async()=>({id:'profile-a'})},careerEventService:{get:async()=>denied(),create:async()=>null,list:async()=>[],update:async()=>null,remove:async()=>null},careerEventAstrologyService:{get:async()=>({unexpected:true})},secureReadingService:{}});const response=await app.inject({url:'/v1/birth-profiles/profile-a/career-events/event-a/astrology',headers:{authorization:'Bearer a'}});assert.equal(response.statusCode,404);assert.equal(response.json().error.code,'NOT_FOUND_OR_FORBIDDEN');assert.equal('astrologySnapshot' in response.json(),false);await app.close();});
