'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createApi } = require('../../src/api');
const { CareerEventService } = require('../../src/application/career-events');
const { createTestOnlyAuthVerifier } = require('../../src/api/test-only-auth-verifier');

const T0 = '2026-08-20T12:00:00.000Z'; const a = { provider: 'supabase', subject: 'a', isAnonymous: false }; const b = { provider: 'supabase', subject: 'b', isAnonymous: false };
function fixture() {
  const rows = []; let ids = 0; const users = { a: { id: 'user-a', status: 'active' }, b: { id: 'user-b', status: 'active' } }; const profiles = { 'profile-a': 'a', 'profile-a2': 'a', 'profile-b': 'b' };
  const events = {
    async create(value) { const row = { ...value, deletedAt: null }; rows.push(row); return row; },
    async listForProfile({ userId, birthProfileId }) { return rows.filter((r) => r.userId === userId && r.birthProfileId === birthProfileId && !r.deletedAt).sort((l, r) => l.eventYear - r.eventYear || (l.eventMonth ?? 0) - (r.eventMonth ?? 0) || (l.eventDay ?? 0) - (r.eventDay ?? 0) || l.createdAt.localeCompare(r.createdAt) || l.id.localeCompare(r.id)); },
    async getForProfile({ userId, birthProfileId, id }) { const row = rows.find((r) => r.id === id && r.userId === userId && r.birthProfileId === birthProfileId && !r.deletedAt); if (!row) { const e = new Error(); e.code = 'CAREER_EVENT_NOT_FOUND'; throw e; } return row; },
    async updateForProfile(value) { const row = await this.getForProfile(value); Object.assign(row, value); return row; },
    async softDeleteForProfile(value) { const row = await this.getForProfile(value); row.deletedAt = value.deletedAt; row.updatedAt = value.updatedAt; return row; },
  };
  const tx = { execute: async ({ operation }) => operation({}) }; const service = new CareerEventService({ authUserResolver: async (p) => users[p.subject], transactionExecutor: tx, repositories: () => ({ careerEvents: events }), birthProfileService: { get: async ({ principal, birthProfileId }) => { if (profiles[birthProfileId] !== principal.subject) { const e = new Error(); e.code = 'NOT_FOUND_OR_FORBIDDEN'; throw e; } return { id: birthProfileId }; } }, idGenerator: () => `career-${++ids}`, clock: () => T0 });
  const api = createApi({ authVerifier: createTestOnlyAuthVerifier({ a, b }), userResolver: { resolve: async () => ({}) }, birthProfileService: { create: async () => ({}), list: async () => [], get: async () => ({}) }, careerEventService: service, secureReadingService: {}, requestIdGenerator: () => 'request-1', corsAllowlist: ['https://app.example.test'] });
  return { api, rows };
}
function request(api, method, url, subject = 'a', payload) { return api.inject({ method, url, headers: { authorization: `Bearer ${subject}` }, payload }); }
const day = { eventType: 'JOB_SWITCH', eventDate: { precision: 'DAY', year: 2021, month: 4, day: 5 }, title: '  Joined Outplay ', notes: ' note ' };
test('CAREER-P1 creates declared DAY, MONTH, and YEAR precision without exposing ownership metadata', async () => { const { api } = fixture(); for (const body of [day, { eventType: 'PROMOTION', eventDate: { precision: 'MONTH', year: 2021, month: 4 } }, { eventType: 'FIRST_JOB', eventDate: { precision: 'YEAR', year: 2021 } }]) assert.equal((await request(api, 'POST', '/v1/birth-profiles/profile-a/career-events', 'a', body)).statusCode, 201); const list = await request(api, 'GET', '/v1/birth-profiles/profile-a/career-events'); assert.deepEqual(list.json().careerEvents.map((v) => v.eventDate.precision), ['YEAR', 'MONTH', 'DAY']); assert.equal(JSON.stringify(list.json()).includes('userId'), false); await api.close(); });
test('CAREER-P1 rejects invalid, future, and client authority event input', async () => { const { api } = fixture(); for (const body of [{ ...day, userId: 'user-b' }, { ...day, extra: true }, { ...day, eventType: 'INVALID' }, { ...day, eventDate: { precision: 'DAY', year: 2021, month: 2, day: 29 } }, { ...day, eventDate: { precision: 'DAY', year: 2027, month: 1, day: 1 } }, { ...day, eventDate: { precision: 'MONTH', year: 2026, month: 9 } }, { ...day, eventDate: { precision: 'YEAR', year: 2027 } }, { ...day, title: 'x'.repeat(161) }, { ...day, notes: 'x'.repeat(2001) }]) assert.equal((await request(api, 'POST', '/v1/birth-profiles/profile-a/career-events', 'a', body)).statusCode, 400); await api.close(); });
test('CAREER-P1 scopes CRUD by profile and user, validates complete PATCH dates, and soft deletes', async () => { const { api, rows } = fixture(); const created = await request(api, 'POST', '/v1/birth-profiles/profile-a/career-events', 'a', day); const id = created.json().careerEvent.careerEventId; const patched = await request(api, 'PATCH', `/v1/birth-profiles/profile-a/career-events/${id}`, 'a', { eventType: 'PROMOTION', eventDate: { precision: 'MONTH', year: 2021, month: 4 } }); assert.equal(patched.statusCode, 200); assert.deepEqual(patched.json().careerEvent.eventDate, { precision: 'MONTH', year: 2021, month: 4, day: null }); assert.equal((await request(api, 'PATCH', `/v1/birth-profiles/profile-a/career-events/${id}`, 'a', { eventDate: { precision: 'MONTH', year: 2021 } })).statusCode, 400); assert.equal((await request(api, 'PATCH', `/v1/birth-profiles/profile-a2/career-events/${id}`, 'a', { title: 'x' })).statusCode, 404); assert.equal((await request(api, 'GET', '/v1/birth-profiles/profile-b/career-events', 'a')).statusCode, 404); const deleted = await request(api, 'DELETE', `/v1/birth-profiles/profile-a/career-events/${id}`); assert.equal(deleted.statusCode, 200); assert.ok(rows[0].deletedAt); assert.equal((await request(api, 'GET', '/v1/birth-profiles/profile-a/career-events')).json().careerEvents.length, 0); assert.equal((await request(api, 'DELETE', `/v1/birth-profiles/profile-a/career-events/${id}`)).statusCode, 404); await api.close(); });
test('CAREER-P1 CORS advertises PATCH and DELETE only with existing configured origin policy', async () => { const { api } = fixture(); const response = await api.inject({ method: 'OPTIONS', url: '/v1/birth-profiles/profile-a/career-events/x', headers: { origin: 'https://app.example.test', 'access-control-request-method': 'PATCH' } }); assert.equal(response.statusCode, 204); assert.match(response.headers['access-control-allow-methods'], /PATCH/); await api.close(); });
