'use strict';

// Opt-in only: disposable PostgreSQL 16 with DB-P2, SEC-P3, SEC-P5, and SEC-P3.1C applied.
const test = require('node:test');
const assert = require('node:assert/strict');
const { Pool } = require('pg');
const { createApiComposition } = require('../../src/api');
const { AstronomicalEngine, AstronomyEngineProvider } = require('../../src/astronomy');
const { PostgresUserKeyEnvelopeStore, UserDekProvider, ReadingPayloadCodec } = require('../../src/security/crypto');
const { PostgresReadingRepository } = require('../../src/persistence');
const { BirthCareerReadingOrchestrator } = require('../../src/orchestration');
const { createResolvedBirthPlace } = require('../../src/place');
const { createReadingRecord } = require('../../src/readings');
const { TestOnlyKms } = require('../security/crypto/test-only-kms');
const { createTestOnlyAuthVerifier } = require('../../src/api/test-only-auth-verifier');

const connectionString = process.env.KUNDLINSIGHTS_API_P1E_DATABASE_URL;
const T0 = '2026-08-13T00:00:00.000Z'; const ROLE = 'api_p1e_server';
const a = Object.freeze({ provider: 'supabase', subject: 'api-p1e-a', isAnonymous: false });
const b = Object.freeze({ provider: 'supabase', subject: 'api-p1e-b', isAnonymous: false });
const birthData = Object.freeze({ localDate: '1990-11-26', localTime: '13:40:00', timezone: 'Asia/Kolkata', utc: '1990-11-26T08:10:00.000Z', latitude: 17.385, longitude: 78.4867, timezoneProvenance: Object.freeze({ provider: 'test', datasetVersion: '2026c', datasetChecksum: 'test' }) });
function headers(token, extra = {}) { return { authorization: `Bearer ${token}`, ...extra }; }
function assertSafe(value) { const text = JSON.stringify(value).toLowerCase(); for (const forbidden of ['ciphertext', 'wrappeddek', 'rawdek', 'kmskeyref', 'auth_subject', 'authsubject', 'connectionstring', 'databaseurl', 'stack', 'sql']) assert.equal(text.includes(forbidden), false, forbidden); }
function sampler(engine) { return Object.freeze({ sampleCanonicalSiderealSun: ({ instantUtc }) => { const date = new Date(instantUtc); const result = engine.calculate({ date: date.toISOString().slice(0, 10), time: date.toISOString().slice(11, 19), timezone: 'UTC', latitude: 0, longitude: 0 }); return Object.freeze({ canonicalSiderealLongitudeDegrees: result.bodies.Sun.siderealLongitudeDegrees, provenance: Object.freeze({ providerId: 'api-p1e-real-astronomy-engine', calculationStatus: 'PROVISIONAL', siderealMode: 'Lahiri / Chitrapaksha', coordinateProvenance: 'derived-from-tropical', productionAuthority: false }) }); } }); }
function scopedProvider(key) { return Object.freeze({ current: async () => ({ keyVersion: key.keyVersion, dek: Buffer.from(key.dek) }), forVersion: async () => ({ keyVersion: key.keyVersion, dek: Buffer.from(key.dek) }) }); }

test('API-P1E real Fastify composition preserves encrypted user-owned Solar reading workflow', { skip: !connectionString, timeout: 600_000 }, async () => {
  const admin = new Pool({ connectionString }); let server; let api; let sequence = 0;
  const idGenerator = () => `api-p1e-${++sequence}-abcdefgh`; const kms = new TestOnlyKms();
  try {
    await admin.query(`drop role if exists ${ROLE}`); await admin.query(`create role ${ROLE} login nosuperuser nobypassrls nocreatedb nocreaterole noinherit`); await admin.query(`grant app_runtime, app_worker, app_crypto to ${ROLE}`);
    await admin.query('truncate app.user_key_envelopes, app.reading_records, app.entitlements, app.payment_transactions, app.birth_profiles, app.users');
    server = new Pool({ connectionString: connectionString.replace('postgresql:///', `postgresql://${ROLE}@/`), max: 1 });
    const engine = new AstronomicalEngine(new AstronomyEngineProvider());
    const composition = createApiComposition({ db: server, authVerifier: createTestOnlyAuthVerifier({ a, b }), kms, astronomicalEngine: engine, canonicalSiderealSunSampler: sampler(engine), idGenerator, clock: () => T0 }); api = composition.api;
    const role = await server.query("select rolsuper,rolbypassrls,rolcanlogin from pg_roles where rolname=session_user"); assert.deepEqual(role.rows[0], { rolsuper: false, rolbypassrls: false, rolcanlogin: true });
    for (const url of ['/health', '/ready']) { const response = await api.inject(url); assert.equal(response.statusCode, 200); assertSafe(response.json()); }
    for (const url of ['/v1/me', '/v1/birth-profiles']) { const response = await api.inject(url); assert.equal(response.statusCode, 401); assert.ok(response.json().requestId); assertSafe(response.json()); }
    const meA = await api.inject({ url: '/v1/me', headers: headers('a') }); const meB = await api.inject({ url: '/v1/me', headers: headers('b') }); assert.equal(meA.statusCode, 200); assert.notEqual(meA.json().user.id, meB.json().user.id); assertSafe(meA.json());
    const profile = await api.inject({ method: 'POST', url: '/v1/birth-profiles', headers: headers('a'), payload: { birthData, userId: meB.json().user.id, ownerId: meB.json().user.id, appUserId: meB.json().user.id } }); assert.equal(profile.statusCode, 201); const profileId = profile.json().birthProfile.id; assertSafe(profile.json());
    const dbProfile = await admin.query('select user_id,birth_payload_ciphertext,birth_payload_key_version from app.birth_profiles where id=$1', [profileId]); assert.equal(dbProfile.rows[0].user_id, meA.json().user.id); assert.equal(Buffer.isBuffer(dbProfile.rows[0].birth_payload_ciphertext), true); assert.ok(dbProfile.rows[0].birth_payload_key_version);
    assert.equal((await api.inject({ url: '/v1/birth-profiles', headers: headers('a') })).json().birthProfiles.length, 1); assert.equal((await api.inject({ url: '/v1/birth-profiles', headers: headers('b') })).json().birthProfiles.length, 0); const forbiddenProfile = await api.inject({ url: `/v1/birth-profiles/${profileId}`, headers: headers('b') }); assert.equal(forbiddenProfile.statusCode, 404); assertSafe(forbiddenProfile.json());
    await admin.query("insert into app.entitlements (id,user_id,product_key,status,quantity,valid_from,valid_until,source_payment_transaction_id,created_at,updated_at) values ('api-p1e-ent',$1,'CAREER','active',2,$2,null,null,$2,$2)", [meA.json().user.id, T0]);
    const request = { method: 'POST', url: '/v1/readings', headers: headers('a', { 'idempotency-key': 'api-p1e-key' }), payload: { birthProfileId: profileId, domain: 'CAREER', readingInstant: T0, locale: 'en-IN' } };
    const generated = await api.inject(request); assert.equal(generated.statusCode, 201); const readingId = generated.json().reading.readingId; assert.equal(generated.json().reading.engineProfileId, 'kundlinsights-vedic-engine-profile-v2'); assertSafe(generated.json());
    const retry = await api.inject(request); assert.equal(retry.statusCode, 201); assert.equal(retry.json().reading.readingId, readingId); assert.equal((await admin.query('select count(*) from app.reading_records where user_id=$1 and idempotency_key=$2', [meA.json().user.id, 'api-p1e-key'])).rows[0].count, '1'); assert.equal((await admin.query("select quantity from app.entitlements where id='api-p1e-ent'")).rows[0].quantity, 1);
    for (const spec of [{ url: `/v1/readings/${readingId}`, method: 'GET' }, { url: `/v1/readings/${readingId}/replay`, method: 'POST' }]) { const response = await api.inject({ ...spec, headers: headers('a') }); assert.equal(response.statusCode, 200); assertSafe(response.json()); }
    for (const spec of [{ url: `/v1/readings/${readingId}`, method: 'GET' }, { url: `/v1/readings/${readingId}/replay`, method: 'POST' }, { url: '/v1/readings', method: 'POST', payload: { birthProfileId: profileId, domain: 'CAREER' } }]) { const response = await api.inject({ ...spec, headers: headers('b', spec.method === 'POST' ? { 'idempotency-key': 'cross-user' } : {}) }); assert.equal(response.statusCode, 404); assertSafe(response.json()); }
    const crypto = (principal, operation) => composition.services.transactionExecutor.execute({ principal, role: 'app_crypto', operation }); kms.setCurrentKeyVersion('test-kek-v2'); await crypto(a, ({ db }) => new UserDekProvider({ kms, envelopeStore: new PostgresUserKeyEnvelopeStore({ db }), idGenerator, now: () => T0 }).rotateUserDek(meA.json().user.id)); assert.equal((await api.inject({ url: `/v1/readings/${readingId}`, headers: headers('a') })).statusCode, 200); assert.equal((await admin.query('select payload_key_version from app.reading_records where id=$1', [readingId])).rows[0].payload_key_version, 'test-kek-v1');
    const concurrentRequest = { ...request, headers: headers('a', { 'idempotency-key': 'api-p1e-concurrent' }) }; const concurrent = await Promise.all([api.inject(concurrentRequest), api.inject(concurrentRequest)]); assert.deepEqual(concurrent.map((response) => response.statusCode), [201, 201]); const concurrentReadingId = concurrent[0].json().reading.readingId; assert.equal(concurrentReadingId, concurrent[1].json().reading.readingId); assert.equal((await admin.query('select count(*) from app.reading_records where user_id=$1 and idempotency_key=$2', [meA.json().user.id, 'api-p1e-concurrent'])).rows[0].count, '1'); assert.equal((await admin.query("select quantity from app.entitlements where id='api-p1e-ent'")).rows[0].quantity, 0);
    for (const spec of [{ url: `/v1/readings/${concurrentReadingId}`, method: 'GET' }, { url: `/v1/readings/${concurrentReadingId}/replay`, method: 'POST' }]) { const response = await api.inject({ ...spec, headers: headers('a') }); assert.equal(response.statusCode, 200); assertSafe(response.json()); }
    const exhaustedNewKey = await api.inject({ ...request, headers: headers('a', { 'idempotency-key': 'api-p1e-exhausted-new-key' }) }); assert.equal(exhaustedNewKey.statusCode, 403); assert.equal(exhaustedNewKey.json().error.code, 'ENTITLEMENT_EXHAUSTED'); assertSafe(exhaustedNewKey.json());
    const place = createResolvedBirthPlace({ provider: 'test', providerPlaceId: profileId, latitude: birthData.latitude, longitude: birthData.longitude, timezone: birthData.timezone, timezoneResolver: birthData.timezoneProvenance });
    const savanaResult = new BirthCareerReadingOrchestrator({ astronomicalEngine: engine, dashaRulesetId: 'vimshottari-longitude-proportional-savana-360-v1' }).generate({ birth: { date: birthData.localDate, time: birthData.localTime, place }, readingInstant: T0, locale: 'en-IN' });
    const savanaRecord = createReadingRecord({ readingId: 'api-p1e-savana-abcdefgh', createdAt: T0, input: { birth: { ...birthData, placeResolution: { resolutionVersion: place.resolutionVersion, timezoneResolver: birthData.timezoneProvenance }, display: null }, readingInstant: T0, transitScanRange: null, locale: 'en-IN' }, result: savanaResult });
    const savanaKey = await crypto(a, ({ db }) => new UserDekProvider({ kms, envelopeStore: new PostgresUserKeyEnvelopeStore({ db }), idGenerator, now: () => T0 }).current(meA.json().user.id)); let encryptedSavana; try { encryptedSavana = await new ReadingPayloadCodec({ userDekProvider: scopedProvider(savanaKey) }).encodeRecord({ userId: meA.json().user.id, record: savanaRecord }); } finally { savanaKey.dek.fill(0); }
    await composition.services.transactionExecutor.execute({ principal: a, role: 'app_runtime', operation: ({ db }) => new PostgresReadingRepository({ db, readingPayloadCodec: { encodeRecord: async () => { throw new Error('unused'); }, decodeRecord: async () => { throw new Error('unused'); } } }).insertEncryptedReadingRecord({ userId: meA.json().user.id, birthProfileId: profileId, record: savanaRecord, encryptedPayload: encryptedSavana, idempotencyKey: 'api-p1e-savana' }) });
    const savanaReplay = await api.inject({ method: 'POST', url: `/v1/readings/${savanaRecord.readingId}/replay`, headers: headers('a') }); assert.equal(savanaReplay.statusCode, 200); assert.equal(savanaReplay.json().replay.replay.result.provenance.dashaRulesetId, 'vimshottari-longitude-proportional-savana-360-v1'); assertSafe(savanaReplay.json());
    const oversized = await api.inject({ method: 'POST', url: '/v1/birth-profiles', headers: headers('a', { 'content-type': 'application/json' }), payload: JSON.stringify({ birthData: { value: 'x'.repeat(17_000) } }) }); assert.equal(oversized.statusCode, 413); assert.ok(oversized.json().requestId); assertSafe(oversized.json());
    const invalid = await api.inject({ method: 'POST', url: '/v1/readings', headers: headers('a'), payload: {} }); assert.equal(invalid.statusCode, 400); assertSafe(invalid.json());
    await assert.rejects(composition.services.transactionExecutor.execute({ principal: a, role: 'app_runtime', operation: ({ db }) => db.query('select * from app.user_key_envelopes') }), (error) => error && error.code === 'AUTHENTICATED_DB_OPERATION_FAILED');
  } finally { await api?.close().catch(() => {}); await server?.end().catch(() => {}); await admin.query(`drop role if exists ${ROLE}`).catch(() => {}); await admin.end(); }
});
