'use strict';
const {classifySiderealLongitude}=require('../jyotish/classify-sidereal-longitude');
const {BODIES,CASTERS,RULESETS}=require('./reference-data'); const {houseFromRashi}=require('./rashi-distance'); const {natalHouseForTransitRashi}=require('./transit-house-mapping'); const {sameRashiNatalBodies}=require('./same-rashi-association'); const {calculateSadeSati}=require('./sade-sati'); const {transitDrishti}=require('./transit-drishti');
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;Object.freeze(v);Object.values(v).forEach(freeze);return v;}
function body(name,input){if(!input||typeof input!=='object')throw new TypeError(`Body ${name} must be an object.`);const a=input.canonicalSiderealLongitudeDegrees,s=input.siderealLongitudeDegrees;if(a!==undefined&&s!==undefined&&a!==s)throw new RangeError(`Body ${name} supplies contradictory canonical sidereal longitudes.`);const lon=a===undefined?s:a;if(typeof lon!=='number'||!Number.isFinite(lon))throw new TypeError(`Body ${name} must provide a finite canonical sidereal longitude.`);const c=classifySiderealLongitude(lon);const supplied=input.rashi===undefined?undefined:typeof input.rashi==='number'?input.rashi:input.rashi&&input.rashi.rashiIndex;if(supplied!==undefined&&supplied!==c.rashi.rashiIndex)throw new RangeError(`Body ${name} supplied Rashi contradicts canonical sidereal longitude.`);const motion=input.motion&&input.motion.providerState!==undefined?input.motion.providerState:input.motion||input.providerState||'unknown';return {body:name,canonicalSiderealLongitudeDegrees:lon,normalizedCanonicalSiderealLongitudeDegrees:c.normalizedLongitudeDegrees,rashi:{rashiIndex:c.rashi.rashiIndex,sanskritName:c.rashi.sanskritName,englishName:c.rashi.englishName,degreesWithinRashi:c.rashi.degreesWithinRashi},motion};}
function validateInstant(v){if(typeof v!=='string'||Number.isNaN(Date.parse(v))||!v.endsWith('Z'))throw new TypeError('snapshotInstant must be a valid UTC timestamp string.');return v;}
function houses(h,natal){if(!h||h.rulesetId!=='parashari-rashi-house-v1'||!Array.isArray(h.houses)||h.houses.length!==12||!h.ascendant||!natal.Ascendant||h.ascendant.rashi.rashiIndex!==natal.Ascendant.rashi.rashiIndex)throw new RangeError('natalHouses must be a valid Layer 5A result consistent with natal Ascendant.');const map={};for(const x of h.houses){if(!x||!x.rashi||!Number.isInteger(x.houseNumber)||map[x.rashi.rashiIndex])throw new RangeError('natalHouses is invalid.');const e=((natal.Ascendant.rashi.rashiIndex+x.houseNumber-2)%12)+1;if(x.rashi.rashiIndex!==e)throw new RangeError('natalHouses is inconsistent with natal Ascendant.');map[x.rashi.rashiIndex]=x.houseNumber;}return map;}
function dignityFor(name,state,result){if(!result)return null;const d=result.bodies&&result.bodies[name];if(!d||d.body!==name||!d.rashi||d.rashi.rashiIndex!==state.rashi.rashiIndex||d.normalizedCanonicalSiderealLongitudeDegrees!==state.normalizedCanonicalSiderealLongitudeDegrees)throw new RangeError(`Transit dignity result contradicts transit body ${name}.`);return d;}
function calculateGocharSnapshot({snapshotInstant,natalBodies,natalHouses,transitBodies,transitDignityResult}={}){const instant=validateInstant(snapshotInstant);if(!natalBodies||!transitBodies)throw new TypeError('natalBodies and transitBodies are required.');const natal=Object.fromEntries(Object.entries(natalBodies).map(([n,v])=>[n,body(n,v)]));if(!natal.Ascendant||!natal.Moon)throw new RangeError('Natal Ascendant and Moon are required.');const hm=houses(natalHouses,natal);const trans={};for(const n of BODIES){if(!transitBodies[n])throw new RangeError(`Transit body ${n} is required.`);const t=body(n,transitBodies[n]);const fromMoon=houseFromRashi(natal.Moon.rashi.rashiIndex,t.rashi.rashiIndex);const edges=CASTERS.includes(n)?transitDrishti(t,natal,hm):[];trans[n]={body:n,transitCanonicalSiderealLongitudeDegrees:t.canonicalSiderealLongitudeDegrees,normalizedTransitCanonicalSiderealLongitudeDegrees:t.normalizedCanonicalSiderealLongitudeDegrees,transitRashi:t.rashi,transitDegreeWithinRashi:t.rashi.degreesWithinRashi,transitNatalHouseNumber:natalHouseForTransitRashi(hm,t.rashi.rashiIndex),houseFromNatalMoon:fromMoon,motion:t.motion,sameRashiNatalBodies:sameRashiNatalBodies(t,natal),aspectsNatalRashis:edges.map(e=>({rashiIndex:e.targetNatalRashiIndex})),aspectsNatalHouses:edges.map(e=>({houseNumber:e.targetNatalHouseNumber})),aspectsNatalBodies:edges,sadeSati:n==='Saturn'?calculateSadeSati(fromMoon):null,transitDignity:dignityFor(n,t,transitDignityResult)};}return freeze({snapshotInstant:instant,rulesets:{transitHouse:RULESETS.transitHouse,fromNatalMoon:RULESETS.fromNatalMoon,sameRashiAssociation:RULESETS.sameRashiAssociation,transitDrishti:RULESETS.transitDrishti,sadeSati:RULESETS.sadeSati},natalContext:{lagnaRashi:natal.Ascendant.rashi,natalMoonRashi:natal.Moon.rashi},transitBodies:trans,provenance:{providerIndependent:true,astronomicalCalculation:'not-performed',ayanamshaCalculation:'not-performed',houseCalculation:'not-performed',dignityCalculation:'not-performed',panchangaCalculation:'not-performed',eventScanning:'not-performed',interpretation:'not-performed'}});}
module.exports={calculateGocharSnapshot};
