'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { AppleNotificationVerifier } = require('../../src/payment/apple/apple-notification-verifier');

const BUNDLE = 'com.kundlinsights.test'; const PRODUCT = 'com.kundlinsights.test.career.annual'; const T = Date.parse('2026-09-01T00:00:00.000Z');
function outer(type = 'SUBSCRIBED', overrides = {}) { return { notificationUUID: 'notification-001', notificationType: type, subtype: 'INITIAL_BUY', version: '2.0', signedDate: T, data: { environment: 'Sandbox', bundleId: BUNDLE, appAppleId: 123, signedTransactionInfo: 'tx-jws', signedRenewalInfo: 'renewal-jws', ...overrides } }; }
function transaction(overrides = {}) { return { bundleId: BUNDLE, environment: 'Sandbox', productId: PRODUCT, transactionId: 'transaction-001', originalTransactionId: 'original-001', purchaseDate: T, expiresDate: T + 86_400_000, signedDate: T, ...overrides }; }
function renewal(overrides = {}) { return { environment: 'Sandbox', productId: PRODUCT, originalTransactionId: 'original-001', autoRenewStatus: 1, expirationIntent: null, renewalDate: T + 86_400_000, gracePeriodExpiresDate: null, signedDate: T, ...overrides }; }
function setup({ notification = outer(), decodedTransaction = transaction(), decodedRenewal = renewal() } = {}) { const calls = []; const verifier = new AppleNotificationVerifier({ signedDataVerifier: { async verifyAndDecodeNotification(value) { calls.push(['outer', value]); if (value.signedPayload === 'bad-outer') { const error = new Error(); error.code = 'APPLE_NOTIFICATION_VERIFICATION_FAILED'; throw error; } return notification; }, async verifyAndDecodeTransaction(value) { calls.push(['transaction', value]); if (value.signedTransaction === 'bad-tx') { const error = new Error(); error.code = 'APPLE_JWS_VERIFICATION_FAILED'; throw error; } return decodedTransaction; }, async verifyAndDecodeRenewalInfo(value) { calls.push(['renewal', value]); if (value.signedRenewalInfo === 'bad-renewal') { const error = new Error(); error.code = 'APPLE_JWS_VERIFICATION_FAILED'; throw error; } return decodedRenewal; } }, bundleId: BUNDLE, appleProductId: PRODUCT }); return { verifier, calls }; }

test('verifies and normalizes each supported Apple notification type without raw JWS values', async () => { for (const type of ['SUBSCRIBED', 'DID_RENEW', 'DID_FAIL_TO_RENEW', 'EXPIRED', 'REFUND', 'REVOKE', 'DID_CHANGE_RENEWAL_STATUS', 'GRACE_PERIOD_EXPIRED', 'RENEWAL_EXTENDED']) { const { verifier, calls } = setup({ notification: outer(type) }); const value = await verifier.verifyAndNormalizeNotification({ signedPayload: 'outer-jws', expectedEnvironment: 'SANDBOX' }); assert.equal(value.providerEventId, 'notification-001'); assert.equal(value.eventType, type); assert.equal(value.eventSubtype, 'INITIAL_BUY'); assert.equal(value.environment, 'SANDBOX'); assert.equal(value.providerEventTime, '2026-09-01T00:00:00.000Z'); assert.equal(value.logicalProductSku, 'career_premium_annual'); assert.equal(value.providerTransactionId, 'transaction-001'); assert.equal(value.originalTransactionId, 'original-001'); assert.equal(value.renewal.autoRenewStatus, 1); assert.deepEqual(calls.map((call) => call[0]), ['outer', 'transaction', 'renewal']); const rendered = JSON.stringify(value); for (const raw of ['outer-jws', 'tx-jws', 'renewal-jws']) assert.equal(rendered.includes(raw), false); } });
test('preserves unknown notification types safely without lifecycle classification', async () => { const { verifier } = setup({ notification: outer('FUTURE_TYPE') }); const value = await verifier.verifyAndNormalizeNotification({ signedPayload: 'outer-jws', expectedEnvironment: 'SANDBOX' }); assert.equal(value.eventType, 'UNKNOWN'); assert.equal(value.sourceNotificationType, 'FUTURE_TYPE'); });
test('rejects invalid outer and nested data, bundle, product, and environment mismatches without trusting client input', async () => { for (const [options, signedPayload, code] of [[{}, 'bad-outer', 'APPLE_NOTIFICATION_VERIFICATION_FAILED'], [{ notification: outer('SUBSCRIBED', { signedTransactionInfo: 'bad-tx' }) }, 'outer-jws', 'APPLE_JWS_VERIFICATION_FAILED'], [{ notification: outer('SUBSCRIBED', { signedRenewalInfo: 'bad-renewal' }) }, 'outer-jws', 'APPLE_JWS_VERIFICATION_FAILED'], [{ notification: outer('SUBSCRIBED', { bundleId: 'com.example.other' }) }, 'outer-jws', 'PURCHASE_EVIDENCE_INVALID'], [{ decodedTransaction: transaction({ productId: 'com.example.other' }) }, 'outer-jws', 'PURCHASE_PRODUCT_UNSUPPORTED'], [{ decodedTransaction: transaction({ environment: 'Production' }) }, 'outer-jws', 'PURCHASE_EVIDENCE_INVALID']]) { const { verifier } = setup(options); await assert.rejects(verifier.verifyAndNormalizeNotification({ signedPayload, expectedEnvironment: 'SANDBOX' }), (error) => error.code === code); } });
test('uses verified notification identity deterministically and rejects environment disagreement', async () => { const { verifier } = setup(); const first = await verifier.verifyAndNormalizeNotification({ signedPayload: 'replay', expectedEnvironment: 'SANDBOX' }); const second = await verifier.verifyAndNormalizeNotification({ signedPayload: 'replay', expectedEnvironment: 'SANDBOX' }); assert.equal(first.providerEventId, second.providerEventId); const { verifier: mismatched } = setup({ notification: outer('SUBSCRIBED', { environment: 'Production' }) }); await assert.rejects(mismatched.verifyAndNormalizeNotification({ signedPayload: 'outer-jws', expectedEnvironment: 'SANDBOX' }), (error) => error.code === 'APPLE_NOTIFICATION_EVIDENCE_INVALID'); });
