'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { GoogleRtdnService } = require('../../src/payment/google/google-rtdn-service');
const { decodeGoogleRtdn } = require('../../src/payment/google/google-rtdn-decoder');
const { InMemoryPaymentEventRepository } = require('../../src/persistence');
const packageName = 'com.kundli.test';
function body(type = 2, token = 'secret-token', messageId = 'event-1') { return { message: { messageId, data: Buffer.from(JSON.stringify({ version: '1.0', packageName, eventTimeMillis: '1788307200000', subscriptionNotification: { version: '1.0', notificationType: type, purchaseToken: token } })).toString('base64') } }; }
function service({ failLookup = false } = {}) { const events = new InMemoryPaymentEventRepository(); let calls = 0; const apiClient = { async getSubscription() { calls++; if (failLookup) throw new Error('down'); return {}; } }; const s = new GoogleRtdnService({ pubsubAuthVerifier: { async verifyRequest() {} }, decoder: decodeGoogleRtdn, apiClient, packageName, googleProductId: 'career.google', paymentEvents: events, lifecycleReconciler: { normalize() { return {}; }, async reconcile() { return { reconciled: false }; } }, idGenerator: () => `id-${calls}`, clock: () => '2026-09-01T00:00:00.000Z' }); return { s, events, get calls() { return calls; } }; }
test('valid trusted RTDN is processed once without returning raw token', async () => { const h = service(); const result = await h.s.handle({ request: { headers: {} }, envelope: body() }); assert.deepEqual(result, { received: true, duplicate: false }); assert.equal(h.calls, 1); assert.equal(JSON.stringify(result).includes('secret-token'), false); const duplicate = await h.s.handle({ request: { headers: {} }, envelope: body() }); assert.equal(duplicate.duplicate, true); });
test('untrusted, test, and transient Google failures are safe', async () => { const h = service(); h.s.pubsubAuthVerifier = { async verifyRequest() { const e = new Error(); e.code = 'GOOGLE_RTDN_UNTRUSTED'; throw e; } }; await assert.rejects(h.s.handle({ request: {}, envelope: body() }), { code: 'GOOGLE_RTDN_UNTRUSTED' }); const retry = service({ failLookup: true }); await assert.rejects(retry.s.handle({ request: {}, envelope: body() }), { code: 'GOOGLE_RTDN_RETRYABLE' }); assert.equal(retry.events.records.values().next().value.processingStatus, 'FAILED'); });
