'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const crypto = require('node:crypto');
const { RazorpayPaymentService } = require('../../src/payment/razorpay/razorpay-payment-service');
const { createRazorpayProductCatalog } = require('../../src/payment/razorpay/razorpay-product-catalog');
const { InMemoryProviderPaymentOrderRepository } = require('../../src/persistence');
const NOW = '2026-09-07T00:00:00.000Z'; const SECRET = 'test-secret';
function setup(payment = { id: 'pay_1', order_id: 'order_1', amount: 12300, currency: 'INR', status: 'captured' }, collection = { items: [] }) { const orders = new InMemoryProviderPaymentOrderRepository(); const persisted = []; let collectionCalls = 0; const service = new RazorpayPaymentService({ authUserResolver: async () => ({ id: 'user_1' }), birthProfileRepository: { getBirthProfile: async () => ({ userId: 'user_1' }) }, providerOrders: orders, razorpayClient: { createOrder: async () => ({ id: 'order_1' }), fetchPayment: async () => payment, fetchPaymentsForOrder: async () => { collectionCalls++; if (collection instanceof Error) throw collection; return collection; } }, productCatalog: createRazorpayProductCatalog([{ logicalSku: 'career_profile_unlock', amountMinor: 12300, currency: 'INR' }]), purchaseService: { persistVerifiedForUser: async ({ normalized }) => { persisted.push(normalized); return { purchase: { id: 'purchase_1' }, entitlement: { career: { eligible: true } } }; }, reconcileRazorpayCareerPremiumProfileEntitlement: async () => null }, unitOfWork: { run: async (fn) => fn({ providerPaymentOrders: orders }) }, idGenerator: (() => { let i = 0; return () => `id_${++i}`; })(), clock: () => NOW, keyId: 'rzp_test_key', keySecret: SECRET, webhookSecret: SECRET }); return { service, orders, persisted, collectionCalls: () => collectionCalls }; }
async function order(s) { return s.service.createOrder({ principal: {}, logicalSku: 'career_profile_unlock', birthProfileId: 'profile_1' }); }
function signature(orderId, paymentId) { return crypto.createHmac('sha256', SECRET).update(`${orderId}|${paymentId}`).digest('hex'); }
test('Razorpay finalizes a captured payment once after HMAC and authoritative amount validation', async () => { const s = setup(); const created = await order(s); const result = await s.service.verifyAndFinalize({ principal: {}, orderId: created.orderId, paymentId: 'pay_1', signature: signature(created.orderId, 'pay_1') }); assert.equal(result.finalized, true); assert.equal(s.persisted.length, 1); await s.service.verifyAndFinalize({ principal: {}, orderId: created.orderId, paymentId: 'pay_1', signature: signature(created.orderId, 'pay_1') }); assert.equal(s.persisted.length, 1); });
test('Razorpay rejects wrong authoritative amount, currency, order, and uncaptured payments', async () => { for (const patch of [{ amount: 1 }, { currency: 'USD' }, { order_id: 'other' }, { status: 'authorized' }]) { const s = setup({ id: 'pay_1', order_id: 'order_1', amount: 12300, currency: 'INR', status: 'captured', ...patch }); const created = await order(s); await assert.rejects(s.service.verifyAndFinalize({ principal: {}, orderId: created.orderId, paymentId: 'pay_1', signature: signature(created.orderId, 'pay_1') })); assert.equal(s.persisted.length, 0); } });
test('status reconciliation returns terminal local orders without provider calls', async () => { const finalized = setup(); const created = await order(finalized); await finalized.orders.markFinalized('id_2', { purchaseRecordId: 'purchase_1', updatedAt: NOW }); const status = await finalized.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'FINALIZED'); assert.equal(finalized.collectionCalls(), 0); const failed = setup(); const failedCreated = await order(failed); await failed.orders.markFailed('id_2', { updatedAt: NOW }); const failedStatus = await failed.service.getOrderStatus({ principal: {}, orderId: failedCreated.orderId }); assert.equal(failedStatus.status, 'FAILED'); assert.equal(failed.collectionCalls(), 0); });
test('status reconciliation fails only zero-payment and all-failed orders', async () => { for (const collection of [{ items: [] }, { items: [{ id: 'pay_1', status: 'failed' }, { id: 'pay_2', status: 'failed' }] }]) { const s = setup(undefined, collection); const created = await order(s); const status = await s.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'FAILED'); assert.equal(status.finalized, false); } });
test('status reconciliation finalizes a matching captured payment through the existing path', async () => { const payment = { id: 'pay_first', order_id: 'order_1', amount: 12300, currency: 'INR', status: 'captured' }; const s = setup(payment, { items: [{ ...payment, created_at: 2 }, { ...payment, id: 'pay_later', created_at: 3 }] }); const created = await order(s); const status = await s.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'FINALIZED'); assert.equal(status.finalized, true); assert.equal(s.persisted.length, 1); assert.equal(s.persisted[0].providerTransactionId, 'pay_first'); });
test('status reconciliation also reconciles a locally paid order', async () => { const payment = { id: 'pay_1', order_id: 'order_1', amount: 12300, currency: 'INR', status: 'captured' }; const s = setup(payment, { items: [payment] }); const created = await order(s); await s.orders.markPaid('id_2', { providerPaymentId: 'pay_1', updatedAt: NOW }); const status = await s.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'FINALIZED'); assert.equal(s.persisted.length, 1); });
test('status reconciliation preserves unresolved orders for mismatched or ambiguous provider evidence', async () => { for (const item of [{ id: 'pay_1', order_id: 'other', amount: 12300, currency: 'INR', status: 'captured' }, { id: 'pay_1', order_id: 'order_1', amount: 1, currency: 'INR', status: 'captured' }, { id: 'pay_1', order_id: 'order_1', amount: 12300, currency: 'USD', status: 'captured' }, { id: 'pay_1', order_id: 'order_1', amount: 12300, currency: 'INR', status: 'authorized' }]) { const s = setup(undefined, { items: [item] }); const created = await order(s); const status = await s.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'CREATED'); assert.equal(s.persisted.length, 0); } });
test('status reconciliation preserves unresolved orders on malformed or failed provider lookups', async () => { for (const collection of [{ unexpected: true }, new Error('transport')]) { const s = setup(undefined, collection); const created = await order(s); const status = await s.service.getOrderStatus({ principal: {}, orderId: created.orderId }); assert.equal(status.status, 'CREATED'); } });
test('status reconciliation retains ownership protection', async () => { const s = setup(); const created = await order(s); s.service.authUserResolver = async () => ({ id: 'other' }); await assert.rejects(s.service.getOrderStatus({ principal: {}, orderId: created.orderId }), (error) => error.code === 'RAZORPAY_ORDER_NOT_FOUND'); });
test('Razorpay webhook and client verification converge without duplicate purchase finalization', async () => { const s = setup(); const created = await order(s); const raw = Buffer.from(JSON.stringify({ event: 'payment.captured', payload: { payment: { entity: { id: 'pay_1', order_id: created.orderId } } } })); const webhookSignature = crypto.createHmac('sha256', SECRET).update(raw).digest('hex'); await s.service.handleWebhook({ rawBody: raw, signature: webhookSignature }); await s.service.verifyAndFinalize({ principal: {}, orderId: created.orderId, paymentId: 'pay_1', signature: signature(created.orderId, 'pay_1') }); assert.equal(s.persisted.length, 1); });
