'use strict';

const { freeze } = require('../synthesis/evidence-node');

const READING_RULESET_ID = 'kundlinsights-deterministic-reading-contract-v1';
const READING_DOMAINS = freeze(['CAREER']);
const SECTION_ORDER = freeze(['CAREER_STRUCTURE', 'CURRENT_DASHA_CONTEXT', 'GOCHAR_CONTEXT', 'TEMPORAL_COACTIVATION', 'CLASSICAL_EVENT_PREDICATES', 'DISCLOSURES']);
const DISCLOSURE_CODES = freeze(['STRUCTURAL_CONTEXT_ONLY', 'TEMPORAL_CONTEXT_ONLY', 'CLASSICAL_PREDICATE_NOT_EVENT_CERTAINTY', 'MISSING_DATA_NEUTRAL', 'CONTRADICTION_PRESENT', 'NO_PROBABILITY_ASSESSMENT', 'NO_OUTCOME_GUARANTEE']);
const TOPIC_SECTIONS = freeze({
  CAREER_H10_SIGNIFICATION_SCOPE_PRESENT: 'CAREER_STRUCTURE',
  CAREER_H10_LORD_NATAL_CONNECTION_PRESENT: 'CAREER_STRUCTURE',
  CAREER_H10_OCCUPANT_CONNECTION_PRESENT: 'CAREER_STRUCTURE',
  CAREER_H2_RESOURCE_CONTEXT_PRESENT: 'CAREER_STRUCTURE',
  CAREER_H11_GAIN_CONTEXT_PRESENT: 'CAREER_STRUCTURE',
  CAREER_H10_CONNECTED_DASHA_ACTIVATION_PRESENT: 'CURRENT_DASHA_CONTEXT',
  CAREER_GOCHAR_CONNECTION_PRESENT: 'GOCHAR_CONTEXT',
  CAREER_TIMING_TRIGGER_CONTEXT_PRESENT: 'GOCHAR_CONTEXT',
  CAREER_TEMPORAL_COACTIVATION_PRESENT: 'TEMPORAL_COACTIVATION',
  CAREER_CLASSICAL_PROFESSIONAL_LOSS_PREDICATE_PRESENT: 'CLASSICAL_EVENT_PREDICATES'
});

module.exports = { READING_RULESET_ID, READING_DOMAINS, SECTION_ORDER, DISCLOSURE_CODES, TOPIC_SECTIONS };
