'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const {loadProductionConfig}=require('../../src/runtime');
const env=()=>({NODE_ENV:'production',HOST:'0.0.0.0',PORT:'3000',DATABASE_URL:'postgresql://user:secret@example.test:5432/db',SUPABASE_DB_CA_BASE64:Buffer.from('test-supabase-ca-certificate').toString('base64'),SUPABASE_AUTH_ISSUER:'https://project.supabase.co/auth/v1',SUPABASE_AUTH_JWKS_URL:'https://project.supabase.co/auth/v1/.well-known/jwks.json',SUPABASE_AUTH_AUDIENCE:'authenticated',SUPABASE_AUTH_ALLOWED_ALGORITHMS:'ES256,RS256',AWS_REGION:'ap-south-1',KUNDLINSIGHTS_KMS_KEY_ARN:'arn:aws:kms:ap-south-1:123456789012:key/11111111-1111-1111-1111-111111111111',GOOGLE_MAPS_API_KEY:'test-google-key',OPENAI_API_KEY:'sk-test-secret',OPENAI_CAREER_MODEL:'fake-model',TIMEZONE_RUNTIME_MANIFEST_PATH:'/runtime/timezones.manifest.json',TIMEZONE_RUNTIME_BINARY_PATH:'/runtime/timezones.bin',CORS_ALLOWED_ORIGINS:'https://app.example.test'});
test('loads strict production configuration without retaining a parsed secret error',()=>{const value=loadProductionConfig(env()); assert.equal(value.db.ssl.rejectUnauthorized,true);assert.equal(value.bodyLimitBytes,16384);assert.equal(value.corsOrigins[0],'https://app.example.test');});
test('rejects invalid production configuration safely',()=>{for(const change of [{DATABASE_URL:'not-a-url'},{OPENAI_API_KEY:''},{OPENAI_CAREER_MODEL:''},{OPENAI_CAREER_TIMEOUT_MS:'99'},{OPENAI_CAREER_TIMEOUT_MS:'30001'},{SUPABASE_AUTH_AUDIENCE:''},{CORS_ALLOWED_ORIGINS:'*'},{PORT:'0'}]){const value=env();Object.assign(value,change);assert.throws(()=>loadProductionConfig(value),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION'&&!e.message.includes('secret'));}});
test('uses the bounded default OpenAI timeout',()=>assert.equal(loadProductionConfig(env()).openai.timeoutMilliseconds,15000));
test('Career Chat kill switch does not require its model, while enabled Chat does',()=>{const disabled=env();delete disabled.CAREER_CHAT_OPENAI_MODEL;const value=loadProductionConfig(disabled);assert.equal(value.careerChat.enabled,false);const enabled=env();enabled.CAREER_CHAT_LLM_ENABLED='true';delete enabled.CAREER_CHAT_OPENAI_MODEL;assert.throws(()=>loadProductionConfig(enabled),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION');});
test('Razorpay requires an explicit trusted environment and retains only supported values',()=>{const configured=env();Object.assign(configured,{RAZORPAY_KEY_ID:'public-key',RAZORPAY_KEY_SECRET:'server-secret',RAZORPAY_WEBHOOK_SECRET:'webhook-secret',RAZORPAY_PRODUCT_CATALOG_JSON:'[]',RAZORPAY_ENVIRONMENT:'SANDBOX'});assert.equal(loadProductionConfig(configured).razorpay.environment,'SANDBOX');configured.RAZORPAY_ENVIRONMENT='PRODUCTION';assert.equal(loadProductionConfig(configured).razorpay.environment,'PRODUCTION');delete configured.RAZORPAY_ENVIRONMENT;assert.throws(()=>loadProductionConfig(configured),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION'&&e.message.includes('RAZORPAY_ENVIRONMENT'));configured.RAZORPAY_ENVIRONMENT='LIVE';assert.throws(()=>loadProductionConfig(configured),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION'&&e.message.includes('RAZORPAY_ENVIRONMENT'));});
test('Apple production purchasing requires the profile-unlock product while preserving optional annual compatibility',()=>{assert.equal(loadProductionConfig(env()).apple,null);const profile={...env(),APPLE_BUNDLE_ID:'com.example.taraverse',APPLE_APP_ID:'123456789',APPLE_ROOT_CERTIFICATE_PATHS:'/deploy/apple-root.pem',APPLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID:'career.profile.unlock'};const profileOnly=loadProductionConfig(profile).apple;assert.equal(profileOnly.careerProfileUnlockProductId,'career.profile.unlock');assert.equal(profileOnly.careerPremiumAnnualProductId,null);const both={...profile,APPLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID:'career.annual'};assert.equal(loadProductionConfig(both).apple.careerPremiumAnnualProductId,'career.annual');const annualOnly={...profile,APPLE_CAREER_PREMIUM_ANNUAL_PRODUCT_ID:'career.annual'};delete annualOnly.APPLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID;assert.throws(()=>loadProductionConfig(annualOnly),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION'&&e.message.includes('APPLE_CAREER_PROFILE_UNLOCK_PRODUCT_ID'));for(const key of ['APPLE_BUNDLE_ID','APPLE_APP_ID','APPLE_ROOT_CERTIFICATE_PATHS']){const partial={...profile};delete partial[key];assert.throws(()=>loadProductionConfig(partial),e=>e.code==='INVALID_PRODUCTION_CONFIGURATION');}});
