'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {CareerFutureRecurrenceService}=require('../../src/application/career-events');
const {AstronomicalEngine}=require('../../src/astronomy');const {scanTransitEvents}=require('../../src/transit-events');const {DeterministicTransitProvider}=require('../transit-events/fixtures/deterministic-transit-provider');
const context={engineProfileId:'kundlinsights-vedic-engine-profile-v2',engineProfileVersion:2,ayanamshaSystem:'fixture-native',nodePolicy:'MEAN_NODE',dashaRulesetId:'vimshottari-longitude-proportional-solar-return-v1',provider:'deterministic-transit-test-provider',providerVersion:'test-v1',ephemerisVersion:'synthetic-piecewise',calculationStatus:'PROVISIONAL'};
const p={patternKey:'p3v1|TRANSIT_RASHI|Jupiter|1|FULL',category:'TRANSIT',primary:true,dimensions:['Jupiter',1,'FULL'],matchedEventCount:2,eligibleEventCount:2,recurrenceRate:1,eventEvidence:[]};
function svc({patterns=[p],clock=()=> '2024-02-01T00:00:00.000Z',scanner=scanTransitEvents}={}){const provider=new DeterministicTransitProvider({trajectories:{Jupiter:[{type:'stationary',startInstant:'1900-01-01T00:00:00.000Z',endInstant:'2024-02-01T00:00:00.000Z',longitudeDegrees:29},{type:'linear',startInstant:'2024-02-01T00:00:00.000Z',endInstant:'2024-02-01T05:00:00.000Z',startLongitudeDegrees:29,longitudeRateDegreesPerDay:12},{type:'stationary',startInstant:'2024-02-01T05:00:00.000Z',endInstant:'2100-01-01T00:00:00.000Z',longitudeDegrees:31}]}});return {provider,service:new CareerFutureRecurrenceService({careerPatternComparisonService:{get:async()=>({comparisonContexts:[{contextKey:'ctx',contextMetadata:context,patterns}]})},birthProfileService:{get:async()=>({id:'p',birthData:{localDate:'2001-01-01',localTime:'00:00:00',timezone:'UTC',latitude:17.385,longitude:78.4867}})},astronomicalEngine:new AstronomicalEngine(provider),canonicalSiderealSunSampler:{sampleCanonicalSiderealSun:()=>({})},ashtakavargaService:{get:async()=>({sav:{signScores:[]},bav:[],lagnaBav:{signScores:[]}})},clock,dashaCalculator:()=>({periods:[]}),transitScanner:scanner})};}
test('uses a 24-calendar-month horizon',async()=>{const {service}=svc();const out=await service.get({principal:{},birthProfileId:'p'});assert.equal(out.horizon.to,'2026-02-01T00:00:00.000Z');});
test('preserves P3 historical evidence',async()=>{const {service}=svc();const out=await service.get({principal:{},birthProfileId:'p'});assert.equal(out.comparisonContexts[0].matches[0].historicalEvidence.matchedEventCount,2);});
test('uses compatible deterministic provenance',async()=>{const {service}=svc();const out=await service.get({principal:{},birthProfileId:'p'});assert.equal(out.comparisonContexts[0].compatibility.status,'COMPATIBLE');});
test('reconstructs a real Jupiter Rashi window from horizon state and scanner ingress chronology',async()=>{let calls=[];const {service}=svc({scanner:(x)=>{calls.push(x);return scanTransitEvents(x);}});const out=await service.get({principal:{},birthProfileId:'p'}),m=out.comparisonContexts[0].matches[0];assert.equal(calls.length,1);assert.equal(m.matchType,'EXACT');assert.equal(m.occurrenceType,'WINDOW');assert.equal(m.from,'2024-02-01T00:00:00.000Z');assert.ok(Math.abs(Date.parse(m.to)-Date.parse('2024-02-01T02:00:00.000Z'))<=1000);assert.deepEqual(calls[0].bodies,['Jupiter']);assert.deepEqual(calls[0].eventTypes,['rashiIngress']);assert.equal(calls[0].options.coarseScanStepMilliseconds,86400000);assert.equal(out.comparisonContexts[0].compatibility.status,'COMPATIBLE');});
