'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { CareerReadingContextBuilder } = require('../../src/application/career-events');

const event = (id, precision = 'DAY', title = 'Title', notes = 'private') => ({ careerEventId: id, birthProfileId: 'profile-a', eventType: 'PROMOTION', eventDate: precision === 'DAY' ? { precision, year: 2020, month: 4, day: 2 } : precision === 'MONTH' ? { precision, year: 2021, month: 4 } : { precision, year: 2022 }, title, notes });
const pattern = (key, category = 'DASHA', matched = 2, rate = 1) => ({ patternKey: key, category, dimensions: ['Jupiter'], matchedEventCount: matched, eligibleEventCount: 2, recurrenceRate: rate, eventEvidence: [{ careerEventId: 'event-a', sourceFacts: { raw: true } }] });
function fixture({ events = [], patterns = [pattern('p1')], matches, composites, status = 'PROVISIONAL' } = {}) {
  const calls = { events: 0, p3: 0, p4: 0 };
  const p3 = { comparisonContexts: [{ contextKey: 'ctx-a', contextMetadata: { calculationStatus: status, providerRequest: { secret: true } }, patterns }], provenance: { rulesetId: 'career-pattern-comparison-v1', raw: true } };
  const p4 = { comparisonContexts: [{ contextKey: 'ctx-a', compatibility: { status: 'COMPATIBLE' }, matches: matches === undefined ? [{ patternKey: 'p1', matchType: 'EXACT', occurrenceType: 'WINDOW', from: '2025-01-01T00:00:00.000Z', to: '2025-02-01T00:00:00.000Z', dimensions: ['Jupiter'], historicalEvidence: { matchedEventCount: 2, eligibleEventCount: 2, recurrenceRate: 1 }, provenance: { calculationStatus: status, scanner: [] } }] : matches, compositeWindows: composites || [] }], provenance: { rulesetId: 'career-future-recurrence-v1', rawScanner: true } };
  return { calls, p3, p4, builder: new CareerReadingContextBuilder({ careerEventService: { list: async () => { calls.events++; return events; } }, careerPatternComparisonService: { get: async () => { calls.p3++; return p3; } }, careerFutureRecurrenceService: { get: async () => { calls.p4++; return p4; } } }) };
}
test('returns factual NONE and LIMITED contexts without P3 or P4', async () => {
  for (const [events, level] of [[[], 'NONE'], [[event('event-a', 'MONTH')], 'LIMITED']]) { const x = fixture({ events }); const out = await x.builder.build({ principal: { id: 'u' }, birthProfileId: 'profile-a' }); assert.equal(out.calibrationLevel, level); assert.equal(out.historicalEvidence.length, 0); assert.equal(out.futureOccurrences.length, 0); assert.equal(out.composites.length, 0); assert.equal(x.calls.p3, 0); assert.equal(x.calls.p4, 0); if (events.length) assert.deepEqual(out.eventReferences[0].eventDate, { precision: 'MONTH', year: 2021, month: 4 }); }
});
test('builds bounded CALIBRATED context from authoritative P3 and P4 results', async () => {
  const x = fixture({ events: [event('event-a'), event('event-b')] }); const out = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.equal(out.calibrationLevel, 'CALIBRATED'); assert.deepEqual(x.calls, { events: 1, p3: 1, p4: 1 }); assert.equal(out.historicalEvidence.length, 1); assert.equal(out.futureOccurrences.length, 1); assert.equal(out.historicalEvidence[0].evidenceId, 'hist:v1:ctx-a:p1'); assert.equal(out.calculationBasis.hasProvisionalEvidence, true); assert.equal(out.rulesets.p3, 'career-pattern-comparison-v1'); assert.equal(out.rulesets.p4, 'career-future-recurrence-v1');
});
test('preserves DAY MONTH YEAR exactly and excludes notes from context', async () => {
  const x = fixture({ events: [event('day', 'DAY'), event('month', 'MONTH'), event('year', 'YEAR')] }); const out = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.deepEqual(out.eventReferences.map((item) => item.eventDate), [{ precision: 'DAY', year: 2020, month: 4, day: 2 }, { precision: 'MONTH', year: 2021, month: 4 }, { precision: 'YEAR', year: 2022 }]); assert.equal(JSON.stringify(out).includes('private'), false);
});
test('title and notes cannot affect factual evidence selection', async () => {
  const a = fixture({ events: [event('a', 'DAY', 'A', 'first'), event('b', 'DAY', 'B', 'second')] }); const b = fixture({ events: [event('a', 'DAY', 'Different', 'changed'), event('b', 'DAY', 'Other', 'changed')] }); const left = await a.builder.build({ principal: {}, birthProfileId: 'profile-a' }), right = await b.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.deepEqual(left.historicalEvidence, right.historicalEvidence); assert.deepEqual(left.futureOccurrences, right.futureOccurrences); assert.notDeepEqual(left.eventReferences, right.eventReferences);
});
test('selects at most twelve historical patterns with category diversity then factual priorities', async () => {
  const patterns = Array.from({ length: 15 }, (_, i) => pattern(`p${i}`, i < 2 ? ['A', 'B'][i] : 'A', i === 0 ? 2 : 3, i === 0 ? 1 : .5)); const x = fixture({ events: [event('a'), event('b')], patterns }); const out = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.equal(out.historicalEvidence.length, 12); assert.deepEqual(out.historicalEvidence.slice(0, 2).map((item) => item.category).sort(), ['A', 'B']); assert.equal(out.historicalEvidence.every((item) => item.matchedEventCount === 3), true); assert.equal(out.historicalEvidence.some((item) => item.patternKey === 'p0'), false);
});
test('limits future evidence across composites then exact chronological occurrences', async () => {
  const composites = Array.from({ length: 2 }, (_, i) => ({ from: `2025-01-0${i + 1}T00:00:00.000Z`, to: `2025-01-0${i + 2}T00:00:00.000Z`, matchedPatternKeys: [`c${i}`], matchedPatternCount: 2, matchedPrimaryPatternCount: 1 })); const matches = Array.from({ length: 15 }, (_, i) => ({ patternKey: `m${i}`, matchType: 'EXACT', occurrenceType: 'EVENT', instant: `2025-02-${String(i + 1).padStart(2, '0')}T00:00:00.000Z`, dimensions: [], historicalEvidence: { matchedEventCount: 2, eligibleEventCount: 2, recurrenceRate: 1 }, provenance: { calculationStatus: 'PROVISIONAL' } })); const x = fixture({ events: [event('a'), event('b')], composites, matches }); const out = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.equal(out.composites.length, 2); assert.equal(out.futureOccurrences.length, 10); assert.equal(out.futureOccurrences[0].patternKey, 'm0'); assert.equal(out.futureOccurrences.at(-1).patternKey, 'm9');
});
test('keeps a calibrated no-pattern result factual and preserves compact composites', async () => {
  const x = fixture({ events: [event('a'), event('b')], patterns: [], matches: [], composites: [{ from: '2025-01-01T00:00:00.000Z', to: '2025-02-01T00:00:00.000Z', matchedPatternKeys: ['a', 'b'], matchedPatternCount: 2, matchedPrimaryPatternCount: 1 }] }); const out = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.equal(out.calibrationLevel, 'CALIBRATED'); assert.deepEqual(out.historicalEvidence, []); assert.deepEqual(out.composites[0].matchedPatternKeys, ['a', 'b']); assert.equal('rawScanner' in out, false);
});
test('is deterministic, fresh, non-mutating, and excludes raw or predictive fields', async () => {
  const x = fixture({ events: [event('a'), event('b')] }); const before = JSON.stringify({ p3: x.p3, p4: x.p4 }); const a = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }), b = await x.builder.build({ principal: {}, birthProfileId: 'profile-a' }); assert.deepEqual(a, b); assert.notEqual(a, b); assert.notEqual(a.eventReferences, b.eventReferences); assert.equal(JSON.stringify({ p3: x.p3, p4: x.p4 }), before); assert.equal(/providerRequest|rawScanner|sourceFacts|score|confidence|probability|prediction|favorable|unfavorable/.test(JSON.stringify(a)), false); assert.deepEqual(x.calls, { events: 2, p3: 2, p4: 2 });
});
