'use strict';

const { fail, requiredString, canonicalTime, immutableCopy } = require('../contracts');
const { freeze } = require('../../synthesis/evidence-node');
const { mapPostgresError } = require('./postgres-errors');
const { profileFingerprint, userFromRow, birthProfileFromRow, paymentFromRow, entitlementFromRow, readingFromRow, encodedBirthPayload, encodedReadingPayload } = require('./postgres-mappers');

const USER_COLUMNS = 'id, auth_subject, status, created_at, updated_at, deleted_at';
const BIRTH_COLUMNS = 'id, user_id, display_label, birth_payload_ciphertext, birth_payload_encryption_version, birth_payload_key_version, birth_payload_algorithm, birth_payload_nonce, status, created_at, updated_at, archived_at';
const PAYMENT_COLUMNS = 'id, user_id, provider, provider_transaction_id, status, amount_minor, currency, created_at, updated_at';
const ENTITLEMENT_COLUMNS = 'id, user_id, product_key, status, quantity, valid_from, valid_until, source_payment_transaction_id, created_at, updated_at';
const READING_COLUMNS = 'id, user_id, birth_profile_id, domain, engine_profile_id, engine_profile_fingerprint, record_schema_version, input_snapshot_ciphertext, provenance_ciphertext, structured_reading_ciphertext, rendered_reading_ciphertext, payload_encryption_version, payload_key_version, payload_algorithm, input_snapshot_nonce, provenance_nonce, structured_reading_nonce, rendered_reading_nonce, integrity_metadata, calculation_digest, output_digest, rendered_output_digest, created_at, archived_at, deleted_at, idempotency_key';

function dbBoundary(db) { if (!db || typeof db.query !== 'function') fail('INVALID_POSTGRES_DB'); return db; }
function codecBoundary(codec, method) { if (!codec || typeof codec[method] !== 'function') fail('INVALID_PERSISTENCE_CODEC'); return codec; }
function now() { return new Date().toISOString(); }
async function queryOne(db, sql, values, notFound) { const result = await db.query(sql, values); if (result.rows.length === 0) fail(notFound); return result.rows[0]; }
async function execute(fn, fallback) { try { return await fn(); } catch (error) { if (error && error.code && /^[A-Z_]+$/.test(error.code)) throw error; throw mapPostgresError(error, fallback); } }
function requiredNullableId(value, code) { return value === null || value === undefined ? null : requiredString(value, code); }
function verifiedRecord(record) {
  if (!record || typeof record !== 'object' || typeof record.readingId !== 'string' || !record.readingId || typeof record.engineProfileId !== 'string' || !record.engineProfileId || !record.integrity || !record.integrity.calculation || !record.integrity.output) fail('INVALID_READING_RECORD');
  return immutableCopy(record, 'INVALID_READING_RECORD');
}

class PostgresUserRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresUserRepository({ db }); }
  async createUser(input = {}) { const id = requiredString(input.id, 'INVALID_USER_ID'); const authSubject = requiredString(input.authSubject, 'INVALID_AUTH_SUBJECT'); const createdAt = canonicalTime(input.createdAt); const updatedAt = canonicalTime(input.updatedAt || input.createdAt); return execute(async () => userFromRow((await this.db.query(`insert into app.users (${USER_COLUMNS}) values ($1, $2, $3, $4, $5, $6) returning ${USER_COLUMNS}`, [id, authSubject, requiredString(input.status || 'active', 'INVALID_STATUS'), createdAt, updatedAt, null])).rows[0]), 'CREATE_USER_FAILED'); }
  async getUser(id) { id = requiredString(id, 'INVALID_USER_ID'); return execute(async () => userFromRow(await queryOne(this.db, `select ${USER_COLUMNS} from app.users where id = $1`, [id], 'USER_NOT_FOUND')), 'GET_USER_FAILED'); }
  async getUserByAuthSubject(authSubject) { authSubject = requiredString(authSubject, 'INVALID_AUTH_SUBJECT'); return execute(async () => { const result = await this.db.query(`select ${USER_COLUMNS} from app.users where auth_subject = $1`, [authSubject]); return result.rows.length ? userFromRow(result.rows[0]) : null; }, 'GET_USER_BY_AUTH_SUBJECT_FAILED'); }
  async updateUserStatus(id, nextStatus, updatedAt) { id = requiredString(id, 'INVALID_USER_ID'); return execute(async () => userFromRow(await queryOne(this.db, `update app.users set status = $2, updated_at = $3 where id = $1 returning ${USER_COLUMNS}`, [id, requiredString(nextStatus, 'INVALID_STATUS'), canonicalTime(updatedAt)], 'USER_NOT_FOUND')), 'UPDATE_USER_FAILED'); }
}

class PostgresBirthProfileRepository {
  constructor({ db, birthProfilePayloadCodec } = {}) { this.db = dbBoundary(db); this.codec = codecBoundary(birthProfilePayloadCodec, 'encodeBirthData'); codecBoundary(this.codec, 'decodeBirthData'); }
  withClient(db) { return new PostgresBirthProfileRepository({ db, birthProfilePayloadCodec: this.codec }); }
  async createBirthProfile(input = {}) { const id = requiredString(input.id, 'INVALID_BIRTH_PROFILE_ID'); const payload = encodedBirthPayload(this.codec, input.birthData); const createdAt = canonicalTime(input.createdAt); const updatedAt = canonicalTime(input.updatedAt || input.createdAt); return execute(async () => birthProfileFromRow((await this.db.query(`insert into app.birth_profiles (${BIRTH_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning ${BIRTH_COLUMNS}`, [id, requiredString(input.userId, 'INVALID_USER_ID'), input.displayLabel == null ? null : requiredString(input.displayLabel, 'INVALID_DISPLAY_LABEL'), payload.ciphertext, payload.encryptionVersion, payload.keyVersion, payload.algorithm, payload.nonce, requiredString(input.status || 'active', 'INVALID_STATUS'), createdAt, updatedAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt)])).rows[0], this.codec), 'CREATE_BIRTH_PROFILE_FAILED'); }
  async getBirthProfile(id) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); return execute(async () => birthProfileFromRow(await queryOne(this.db, `select ${BIRTH_COLUMNS} from app.birth_profiles where id = $1`, [id], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'GET_BIRTH_PROFILE_FAILED'); }
  async listBirthProfilesForUser(userId) { userId = requiredString(userId, 'INVALID_USER_ID'); return execute(async () => freeze((await this.db.query(`select ${BIRTH_COLUMNS} from app.birth_profiles where user_id = $1 order by created_at asc, id asc`, [userId])).rows.map((row) => birthProfileFromRow(row, this.codec))), 'LIST_BIRTH_PROFILES_FAILED'); }
  async updateBirthProfile(id, changes = {}) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); if ('userId' in changes || 'id' in changes || 'createdAt' in changes || 'archivedAt' in changes || 'status' in changes) fail('INVALID_BIRTH_PROFILE_UPDATE'); const prior = await this.getBirthProfile(id); const payload = encodedBirthPayload(this.codec, 'birthData' in changes ? changes.birthData : prior.birthData); return execute(async () => birthProfileFromRow(await queryOne(this.db, `update app.birth_profiles set display_label=$2,birth_payload_ciphertext=$3,birth_payload_encryption_version=$4,birth_payload_key_version=$5,birth_payload_algorithm=$6,birth_payload_nonce=$7,updated_at=$8 where id=$1 returning ${BIRTH_COLUMNS}`, [id, 'displayLabel' in changes ? (changes.displayLabel == null ? null : requiredString(changes.displayLabel, 'INVALID_DISPLAY_LABEL')) : prior.displayLabel, payload.ciphertext, payload.encryptionVersion, payload.keyVersion, payload.algorithm, payload.nonce, canonicalTime(changes.updatedAt)], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'UPDATE_BIRTH_PROFILE_FAILED'); }
  async archiveBirthProfile(id, archivedAt) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); const at = canonicalTime(archivedAt, 'INVALID_ARCHIVED_AT'); return execute(async () => birthProfileFromRow(await queryOne(this.db, `update app.birth_profiles set status='archived',archived_at=$2,updated_at=$2 where id=$1 returning ${BIRTH_COLUMNS}`, [id, at], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'ARCHIVE_BIRTH_PROFILE_FAILED'); }
}

class PostgresReadingRepository {
  constructor({ db, readingPayloadCodec } = {}) { this.db = dbBoundary(db); this.codec = codecBoundary(readingPayloadCodec, 'encodeRecord'); codecBoundary(this.codec, 'decodeRecord'); }
  withClient(db) { return new PostgresReadingRepository({ db, readingPayloadCodec: this.codec }); }
  async insertReadingRecord(input = {}) { const record = verifiedRecord(input.record); const payload = encodedReadingPayload(this.codec, record); const renderedDigest = record.integrity.rendered ? record.integrity.rendered.digest : null; return execute(async () => readingFromRow((await this.db.query(`insert into app.reading_records (${READING_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) returning ${READING_COLUMNS}`, [record.readingId, requiredString(input.userId, 'INVALID_USER_ID'), requiredNullableId(input.birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), requiredString(record.domain, 'INVALID_READING_RECORD'), record.engineProfileId, profileFingerprint(record.engineProfileId), record.schemaVersion, payload.inputSnapshotCiphertext, payload.provenanceCiphertext, payload.structuredReadingCiphertext, payload.renderedReadingCiphertext, payload.payloadEncryptionVersion, payload.payloadKeyVersion, payload.payloadAlgorithm, payload.inputSnapshotNonce, payload.provenanceNonce, payload.structuredReadingNonce, payload.renderedReadingNonce, payload.integrityMetadata, record.integrity.calculation.digest, record.integrity.output.digest, renderedDigest, record.createdAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt), null, input.idempotencyKey == null ? null : requiredString(input.idempotencyKey, 'INVALID_IDEMPOTENCY_KEY')])).rows[0], this.codec), 'INSERT_READING_FAILED'); }
  async getReadingRecord(readingId) { readingId = requiredString(readingId, 'INVALID_READING_ID'); return execute(async () => readingFromRow(await queryOne(this.db, `select ${READING_COLUMNS} from app.reading_records where id=$1`, [readingId], 'READING_NOT_FOUND'), this.codec), 'GET_READING_FAILED'); }
  async listReadingRecordsForUser(userId) { userId = requiredString(userId, 'INVALID_USER_ID'); return execute(async () => freeze((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where user_id=$1 order by created_at desc,id asc`, [userId])).rows.map((row) => readingFromRow(row, this.codec))), 'LIST_READINGS_FAILED'); }
  async listReadingRecordsForBirthProfile(birthProfileId) { birthProfileId = requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID'); return execute(async () => freeze((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where birth_profile_id=$1 order by created_at desc,id asc`, [birthProfileId])).rows.map((row) => readingFromRow(row, this.codec))), 'LIST_READINGS_FAILED'); }
  async archiveReadingRecord(readingId, archivedAt) { readingId = requiredString(readingId, 'INVALID_READING_ID'); return execute(async () => readingFromRow(await queryOne(this.db, `update app.reading_records set archived_at=$2 where id=$1 returning ${READING_COLUMNS}`, [readingId, canonicalTime(archivedAt, 'INVALID_ARCHIVED_AT')], 'READING_NOT_FOUND'), this.codec), 'ARCHIVE_READING_FAILED'); }
}

class PostgresEntitlementRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresEntitlementRepository({ db }); }
  async createEntitlement(input = {}) { const id = requiredString(input.id, 'INVALID_ENTITLEMENT_ID'); const validFrom = canonicalTime(input.validFrom, 'INVALID_ENTITLEMENT_VALIDITY'); const validUntil = input.validUntil == null ? null : canonicalTime(input.validUntil, 'INVALID_ENTITLEMENT_VALIDITY'); if (validUntil && Date.parse(validUntil) <= Date.parse(validFrom)) fail('INVALID_ENTITLEMENT_VALIDITY'); const createdAt = input.createdAt == null ? now() : canonicalTime(input.createdAt); const updatedAt = input.updatedAt == null ? createdAt : canonicalTime(input.updatedAt); return execute(async () => entitlementFromRow((await this.db.query(`insert into app.entitlements (${ENTITLEMENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning ${ENTITLEMENT_COLUMNS}`, [id, requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.productKey, 'INVALID_PRODUCT_KEY'), requiredString(input.status || 'active', 'INVALID_STATUS'), input.quantity, validFrom, validUntil, requiredNullableId(input.sourcePaymentTransactionId, 'INVALID_PAYMENT_TRANSACTION_ID'), createdAt, updatedAt])).rows[0]), 'CREATE_ENTITLEMENT_FAILED'); }
  async getEntitlement(id) { id = requiredString(id, 'INVALID_ENTITLEMENT_ID'); return execute(async () => entitlementFromRow(await queryOne(this.db, `select ${ENTITLEMENT_COLUMNS} from app.entitlements where id=$1`, [id], 'ENTITLEMENT_NOT_FOUND')), 'GET_ENTITLEMENT_FAILED'); }
  async listActiveEntitlementsForUser(userId, evaluationTime) { userId = requiredString(userId, 'INVALID_USER_ID'); const at = canonicalTime(evaluationTime, 'INVALID_EVALUATION_TIME'); return execute(async () => freeze((await this.db.query(`select ${ENTITLEMENT_COLUMNS} from app.entitlements where user_id=$1 and status='active' and quantity>0 and valid_from <= $2 and (valid_until is null or valid_until > $2) order by valid_from asc,id asc`, [userId, at])).rows.map(entitlementFromRow)), 'LIST_ENTITLEMENTS_FAILED'); }
  async consumeEntitlement(id, evaluationTime) { id = requiredString(id, 'INVALID_ENTITLEMENT_ID'); const at = canonicalTime(evaluationTime, 'INVALID_EVALUATION_TIME'); return execute(async () => { const updated = await this.db.query(`update app.entitlements set quantity=quantity-1,updated_at=$2 where id=$1 and quantity>0 and status='active' and valid_from <= $2 and (valid_until is null or valid_until > $2) returning ${ENTITLEMENT_COLUMNS}`, [id, at]); if (updated.rows.length) return entitlementFromRow(updated.rows[0]); const prior = await this.db.query(`select status,quantity,valid_from,valid_until from app.entitlements where id=$1`, [id]); if (!prior.rows.length) fail('ENTITLEMENT_NOT_FOUND'); const row = prior.rows[0]; if (row.status !== 'active') fail('ENTITLEMENT_INACTIVE'); if (Date.parse(row.valid_from) > Date.parse(at) || (row.valid_until && Date.parse(row.valid_until) <= Date.parse(at))) fail('ENTITLEMENT_EXPIRED'); fail('ENTITLEMENT_EXHAUSTED'); }, 'CONSUME_ENTITLEMENT_FAILED'); }
}

class PostgresPaymentRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresPaymentRepository({ db }); }
  async insertPaymentTransaction(input = {}) { const id = requiredString(input.id, 'INVALID_PAYMENT_TRANSACTION_ID'); if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor < 0 || typeof input.currency !== 'string' || !/^[A-Z]{3}$/.test(input.currency)) fail('INVALID_PAYMENT_AMOUNT'); const createdAt = canonicalTime(input.createdAt); const updatedAt = input.updatedAt == null ? createdAt : canonicalTime(input.updatedAt); return execute(async () => paymentFromRow((await this.db.query(`insert into app.payment_transactions (${PAYMENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning ${PAYMENT_COLUMNS}`, [id, requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.provider, 'INVALID_PAYMENT_PROVIDER'), requiredString(input.providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID'), requiredString(input.status || 'created', 'INVALID_STATUS'), input.amountMinor, input.currency, createdAt, updatedAt])).rows[0]), 'INSERT_PAYMENT_FAILED'); }
  async getPaymentTransaction(id) { id = requiredString(id, 'INVALID_PAYMENT_TRANSACTION_ID'); return execute(async () => paymentFromRow(await queryOne(this.db, `select ${PAYMENT_COLUMNS} from app.payment_transactions where id=$1`, [id], 'PAYMENT_TRANSACTION_NOT_FOUND')), 'GET_PAYMENT_FAILED'); }
  async findByProviderTransactionId(provider, providerTransactionId) { provider = requiredString(provider, 'INVALID_PAYMENT_PROVIDER'); providerTransactionId = requiredString(providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID'); return execute(async () => { const result = await this.db.query(`select ${PAYMENT_COLUMNS} from app.payment_transactions where provider=$1 and provider_transaction_id=$2`, [provider, providerTransactionId]); return result.rows.length ? paymentFromRow(result.rows[0]) : null; }, 'FIND_PAYMENT_FAILED'); }
}

module.exports = { PostgresUserRepository, PostgresBirthProfileRepository, PostgresReadingRepository, PostgresEntitlementRepository, PostgresPaymentRepository, profileFingerprint, mapPostgresError };
