'use strict';

const { fail, requiredString, canonicalTime, immutableCopy } = require('../contracts');
const { freeze } = require('../../synthesis/evidence-node');
const { mapPostgresError } = require('./postgres-errors');
const { profileFingerprint, userFromRow, birthProfileFromRow, encryptedBirthProfileFromRow, paymentFromRow, purchaseFromRow, subscriptionFromRow, paymentEventFromRow, entitlementFromRow, careerEventFromRow, readingFromRow, encryptedReadingFromRow, encodedBirthPayload, encodedReadingPayload } = require('./postgres-mappers');
const { purchaseRecord, subscriptionRecord, paymentEvent } = require('../../payment');

const USER_COLUMNS = 'id, auth_subject, status, created_at, updated_at, deleted_at';
const BIRTH_COLUMNS = 'id, user_id, display_label, birth_payload_ciphertext, birth_payload_encryption_version, birth_payload_key_version, birth_payload_algorithm, birth_payload_nonce, status, created_at, updated_at, archived_at';
const PAYMENT_COLUMNS = 'id, user_id, provider, provider_transaction_id, status, amount_minor, currency, created_at, updated_at';
const PURCHASE_COLUMNS = 'id,user_id,provider,environment,product_id,provider_transaction_id,original_transaction_id,status,purchased_at,valid_from,valid_until,verified_at,payment_transaction_id,created_at,updated_at';
const SUBSCRIPTION_COLUMNS = 'id,user_id,provider,environment,product_id,original_transaction_id,status,valid_from,valid_until,auto_renew_enabled,grace_until,canceled_at,revoked_at,refunded_at,latest_purchase_record_id,provider_event_time,provider_event_version,created_at,updated_at';
const EVENT_COLUMNS = 'id,provider,environment,provider_event_id,event_type,provider_event_time,purchase_record_id,subscription_record_id,received_at,processed_at,processing_status,failure_code,payload_digest,created_at';
const ENTITLEMENT_COLUMNS = 'id, user_id, product_key, status, quantity, valid_from, valid_until, source_payment_transaction_id, created_at, updated_at';
const CAREER_EVENT_COLUMNS = 'id, user_id, birth_profile_id, event_type, event_date_precision, event_year, event_month, event_day, title, notes, created_at, updated_at, deleted_at';
const READING_COLUMNS = 'id, user_id, birth_profile_id, domain, engine_profile_id, engine_profile_fingerprint, record_schema_version, input_snapshot_ciphertext, provenance_ciphertext, structured_reading_ciphertext, rendered_reading_ciphertext, payload_encryption_version, payload_key_version, payload_algorithm, input_snapshot_nonce, provenance_nonce, structured_reading_nonce, rendered_reading_nonce, integrity_metadata, calculation_digest, output_digest, rendered_output_digest, created_at, archived_at, deleted_at, idempotency_key';

function dbBoundary(db) { if (!db || typeof db.query !== 'function') fail('INVALID_POSTGRES_DB'); return db; }
function codecBoundary(codec, method) { if (!codec || typeof codec[method] !== 'function') fail('INVALID_PERSISTENCE_CODEC'); return codec; }
function now() { return new Date().toISOString(); }
async function queryOne(db, sql, values, notFound) { const result = await db.query(sql, values); if (result.rows.length === 0) fail(notFound); return result.rows[0]; }
async function execute(fn, fallback) { try { return await fn(); } catch (error) { if (error && error.code && /^[A-Z_]+$/.test(error.code)) throw error; throw mapPostgresError(error, fallback); } }
function requiredNullableId(value, code) { return value === null || value === undefined ? null : requiredString(value, code); }
function verifiedRecord(record) {
  if (!record || typeof record !== 'object' || typeof record.readingId !== 'string' || !record.readingId || typeof record.engineProfileId !== 'string' || !record.engineProfileId || !record.integrity || !record.integrity.calculation || !record.integrity.output) fail('INVALID_READING_RECORD');
  return immutableCopy(record, 'INVALID_READING_RECORD');
}

class PostgresUserRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresUserRepository({ db }); }
  async createUser(input = {}) { const id = requiredString(input.id, 'INVALID_USER_ID'); const authSubject = requiredString(input.authSubject, 'INVALID_AUTH_SUBJECT'); const createdAt = canonicalTime(input.createdAt); const updatedAt = canonicalTime(input.updatedAt || input.createdAt); return execute(async () => { await this.db.query(`insert into app.users (${USER_COLUMNS}) values ($1, $2, $3, $4, $5, $6) on conflict (auth_subject) do nothing`, [id, authSubject, requiredString(input.status || 'active', 'INVALID_STATUS'), createdAt, updatedAt, null]); const user = await this.getUserByAuthSubject(authSubject); if (!user) fail('USER_NOT_FOUND'); return user; }, 'CREATE_USER_FAILED'); }
  async getUser(id) { id = requiredString(id, 'INVALID_USER_ID'); return execute(async () => userFromRow(await queryOne(this.db, `select ${USER_COLUMNS} from app.users where id = $1`, [id], 'USER_NOT_FOUND')), 'GET_USER_FAILED'); }
  async getUserByAuthSubject(authSubject) { authSubject = requiredString(authSubject, 'INVALID_AUTH_SUBJECT'); return execute(async () => { const result = await this.db.query(`select ${USER_COLUMNS} from app.users where auth_subject = $1`, [authSubject]); return result.rows.length ? userFromRow(result.rows[0]) : null; }, 'GET_USER_BY_AUTH_SUBJECT_FAILED'); }
  async updateUserStatus(id, nextStatus, updatedAt) { id = requiredString(id, 'INVALID_USER_ID'); return execute(async () => userFromRow(await queryOne(this.db, `update app.users set status = $2, updated_at = $3 where id = $1 returning ${USER_COLUMNS}`, [id, requiredString(nextStatus, 'INVALID_STATUS'), canonicalTime(updatedAt)], 'USER_NOT_FOUND')), 'UPDATE_USER_FAILED'); }
}

class PostgresBirthProfileRepository {
  constructor({ db, birthProfilePayloadCodec } = {}) { this.db = dbBoundary(db); this.codec = codecBoundary(birthProfilePayloadCodec, 'encodeBirthData'); codecBoundary(this.codec, 'decodeBirthData'); }
  withClient(db) { return new PostgresBirthProfileRepository({ db, birthProfilePayloadCodec: this.codec }); }
  async createEncryptedBirthProfile(input = {}) { const id = requiredString(input.id, 'INVALID_BIRTH_PROFILE_ID'); const userId = requiredString(input.userId, 'INVALID_USER_ID'); const payload = input.encryptedPayload; if (!payload || !Buffer.isBuffer(payload.ciphertext) || !Buffer.isBuffer(payload.nonce) || typeof payload.encryptionVersion !== 'number' || typeof payload.keyVersion !== 'string' || typeof payload.algorithm !== 'string') fail('INVALID_CODEC_PAYLOAD'); const createdAt = canonicalTime(input.createdAt); const updatedAt = canonicalTime(input.updatedAt || input.createdAt); return execute(async () => encryptedBirthProfileFromRow((await this.db.query(`insert into app.birth_profiles (${BIRTH_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning ${BIRTH_COLUMNS}`, [id, userId, input.displayLabel == null ? null : requiredString(input.displayLabel, 'INVALID_DISPLAY_LABEL'), payload.ciphertext, payload.encryptionVersion, payload.keyVersion, payload.algorithm, payload.nonce, requiredString(input.status || 'active', 'INVALID_STATUS'), createdAt, updatedAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt)])).rows[0]), 'CREATE_BIRTH_PROFILE_FAILED'); }
  async getEncryptedBirthProfile(id) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); return execute(async () => encryptedBirthProfileFromRow(await queryOne(this.db, `select ${BIRTH_COLUMNS} from app.birth_profiles where id = $1`, [id], 'BIRTH_PROFILE_NOT_FOUND')), 'GET_BIRTH_PROFILE_FAILED'); }
  async listEncryptedBirthProfilesForUser(userId) { userId = requiredString(userId, 'INVALID_USER_ID'); return execute(async () => freeze((await this.db.query(`select ${BIRTH_COLUMNS} from app.birth_profiles where user_id = $1 order by created_at asc, id asc`, [userId])).rows.map(encryptedBirthProfileFromRow)), 'LIST_BIRTH_PROFILES_FAILED'); }
  async createBirthProfile(input = {}) { const id = requiredString(input.id, 'INVALID_BIRTH_PROFILE_ID'); const userId = requiredString(input.userId, 'INVALID_USER_ID'); const payload = await encodedBirthPayload(this.codec, { userId, profileId: id, birthData: input.birthData }); const createdAt = canonicalTime(input.createdAt); const updatedAt = canonicalTime(input.updatedAt || input.createdAt); return execute(async () => birthProfileFromRow((await this.db.query(`insert into app.birth_profiles (${BIRTH_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning ${BIRTH_COLUMNS}`, [id, userId, input.displayLabel == null ? null : requiredString(input.displayLabel, 'INVALID_DISPLAY_LABEL'), payload.ciphertext, payload.encryptionVersion, payload.keyVersion, payload.algorithm, payload.nonce, requiredString(input.status || 'active', 'INVALID_STATUS'), createdAt, updatedAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt)])).rows[0], this.codec), 'CREATE_BIRTH_PROFILE_FAILED'); }
  async getBirthProfile(id) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); return execute(async () => birthProfileFromRow(await queryOne(this.db, `select ${BIRTH_COLUMNS} from app.birth_profiles where id = $1`, [id], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'GET_BIRTH_PROFILE_FAILED'); }
  async listBirthProfilesForUser(userId) { userId = requiredString(userId, 'INVALID_USER_ID'); return execute(async () => freeze(await Promise.all((await this.db.query(`select ${BIRTH_COLUMNS} from app.birth_profiles where user_id = $1 order by created_at asc, id asc`, [userId])).rows.map((row) => birthProfileFromRow(row, this.codec)))), 'LIST_BIRTH_PROFILES_FAILED'); }
  async updateBirthProfile(id, changes = {}) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); if ('userId' in changes || 'id' in changes || 'createdAt' in changes || 'archivedAt' in changes || 'status' in changes) fail('INVALID_BIRTH_PROFILE_UPDATE'); const prior = await this.getBirthProfile(id); const payload = await encodedBirthPayload(this.codec, { userId: prior.userId, profileId: id, birthData: 'birthData' in changes ? changes.birthData : prior.birthData }); return execute(async () => birthProfileFromRow(await queryOne(this.db, `update app.birth_profiles set display_label=$2,birth_payload_ciphertext=$3,birth_payload_encryption_version=$4,birth_payload_key_version=$5,birth_payload_algorithm=$6,birth_payload_nonce=$7,updated_at=$8 where id=$1 returning ${BIRTH_COLUMNS}`, [id, 'displayLabel' in changes ? (changes.displayLabel == null ? null : requiredString(changes.displayLabel, 'INVALID_DISPLAY_LABEL')) : prior.displayLabel, payload.ciphertext, payload.encryptionVersion, payload.keyVersion, payload.algorithm, payload.nonce, canonicalTime(changes.updatedAt)], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'UPDATE_BIRTH_PROFILE_FAILED'); }
  async archiveBirthProfile(id, archivedAt) { id = requiredString(id, 'INVALID_BIRTH_PROFILE_ID'); const at = canonicalTime(archivedAt, 'INVALID_ARCHIVED_AT'); return execute(async () => birthProfileFromRow(await queryOne(this.db, `update app.birth_profiles set status='archived',archived_at=$2,updated_at=$2 where id=$1 returning ${BIRTH_COLUMNS}`, [id, at], 'BIRTH_PROFILE_NOT_FOUND'), this.codec), 'ARCHIVE_BIRTH_PROFILE_FAILED'); }
}

class PostgresReadingRepository {
  constructor({ db, readingPayloadCodec } = {}) { this.db = dbBoundary(db); this.codec = codecBoundary(readingPayloadCodec, 'encodeRecord'); codecBoundary(this.codec, 'decodeRecord'); }
  withClient(db) { return new PostgresReadingRepository({ db, readingPayloadCodec: this.codec }); }
  async insertEncryptedReadingRecord(input = {}) { const record = verifiedRecord(input.record); const userId = requiredString(input.userId, 'INVALID_USER_ID'); const payload = input.encryptedPayload; if (!payload || !Buffer.isBuffer(payload.inputSnapshotCiphertext) || !Buffer.isBuffer(payload.provenanceCiphertext) || !Buffer.isBuffer(payload.structuredReadingCiphertext) || !Buffer.isBuffer(payload.inputSnapshotNonce) || !Buffer.isBuffer(payload.provenanceNonce) || !Buffer.isBuffer(payload.structuredReadingNonce)) fail('INVALID_CODEC_PAYLOAD'); const renderedDigest = record.integrity.rendered ? record.integrity.rendered.digest : null; return execute(async () => encryptedReadingFromRow((await this.db.query(`insert into app.reading_records (${READING_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) returning ${READING_COLUMNS}`, [record.readingId, userId, input.birthProfileId == null ? null : requiredNullableId(input.birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), requiredString(record.domain, 'INVALID_READING_RECORD'), record.engineProfileId, profileFingerprint(record.engineProfileId), record.schemaVersion, payload.inputSnapshotCiphertext, payload.provenanceCiphertext, payload.structuredReadingCiphertext, payload.renderedReadingCiphertext, payload.payloadEncryptionVersion, payload.payloadKeyVersion, payload.payloadAlgorithm, payload.inputSnapshotNonce, payload.provenanceNonce, payload.structuredReadingNonce, payload.renderedReadingNonce, payload.integrityMetadata, record.integrity.calculation.digest, record.integrity.output.digest, renderedDigest, record.createdAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt), null, input.idempotencyKey == null ? null : requiredString(input.idempotencyKey, 'INVALID_IDEMPOTENCY_KEY')])).rows[0]), 'INSERT_READING_FAILED'); }
  async getEncryptedReadingRecord(readingId) { readingId = requiredString(readingId, 'INVALID_READING_ID'); return execute(async () => encryptedReadingFromRow(await queryOne(this.db, `select ${READING_COLUMNS} from app.reading_records where id=$1`, [readingId], 'READING_NOT_FOUND')), 'GET_READING_FAILED'); }
  async getEncryptedReadingRecordByIdempotencyKey(userId, idempotencyKey) { userId = requiredString(userId, 'INVALID_USER_ID'); idempotencyKey = requiredString(idempotencyKey, 'INVALID_IDEMPOTENCY_KEY'); return execute(async () => { const result = await this.db.query(`select ${READING_COLUMNS} from app.reading_records where user_id=$1 and idempotency_key=$2`, [userId, idempotencyKey]); return result.rows.length ? encryptedReadingFromRow(result.rows[0]) : null; }, 'GET_READING_FAILED'); }
  async listEncryptedReadingRecordsForUser(userId, limit) { userId = requiredString(userId, 'INVALID_USER_ID'); if (!Number.isInteger(limit) || limit < 1 || limit > 50) fail('INVALID_READING_LIST_LIMIT'); return execute(async () => freeze((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where user_id=$1 order by created_at desc,id asc limit $2`, [userId, limit])).rows.map(encryptedReadingFromRow)), 'LIST_READINGS_FAILED'); }
  async listEncryptedReadingRecordsForBirthProfile(birthProfileId, limit) { birthProfileId = requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID'); if (!Number.isInteger(limit) || limit < 1 || limit > 50) fail('INVALID_READING_LIST_LIMIT'); return execute(async () => freeze((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where birth_profile_id=$1 order by created_at desc,id asc limit $2`, [birthProfileId, limit])).rows.map(encryptedReadingFromRow)), 'LIST_READINGS_FAILED'); }
  async insertReadingRecord(input = {}) { const record = verifiedRecord(input.record); const userId = requiredString(input.userId, 'INVALID_USER_ID'); const payload = await encodedReadingPayload(this.codec, { userId, record }); const renderedDigest = record.integrity.rendered ? record.integrity.rendered.digest : null; return execute(async () => readingFromRow((await this.db.query(`insert into app.reading_records (${READING_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) returning ${READING_COLUMNS}`, [record.readingId, userId, requiredNullableId(input.birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), requiredString(record.domain, 'INVALID_READING_RECORD'), record.engineProfileId, profileFingerprint(record.engineProfileId), record.schemaVersion, payload.inputSnapshotCiphertext, payload.provenanceCiphertext, payload.structuredReadingCiphertext, payload.renderedReadingCiphertext, payload.payloadEncryptionVersion, payload.payloadKeyVersion, payload.payloadAlgorithm, payload.inputSnapshotNonce, payload.provenanceNonce, payload.structuredReadingNonce, payload.renderedReadingNonce, payload.integrityMetadata, record.integrity.calculation.digest, record.integrity.output.digest, renderedDigest, record.createdAt, input.archivedAt == null ? null : canonicalTime(input.archivedAt), null, input.idempotencyKey == null ? null : requiredString(input.idempotencyKey, 'INVALID_IDEMPOTENCY_KEY')])).rows[0], this.codec), 'INSERT_READING_FAILED'); }
  async getReadingRecord(readingId) { readingId = requiredString(readingId, 'INVALID_READING_ID'); return execute(async () => readingFromRow(await queryOne(this.db, `select ${READING_COLUMNS} from app.reading_records where id=$1`, [readingId], 'READING_NOT_FOUND'), this.codec), 'GET_READING_FAILED'); }
  async getReadingRecordByIdempotencyKey(userId, idempotencyKey) { userId = requiredString(userId, 'INVALID_USER_ID'); idempotencyKey = requiredString(idempotencyKey, 'INVALID_IDEMPOTENCY_KEY'); return execute(async () => { const result = await this.db.query(`select ${READING_COLUMNS} from app.reading_records where user_id=$1 and idempotency_key=$2`, [userId, idempotencyKey]); return result.rows.length ? readingFromRow(result.rows[0], this.codec) : null; }, 'GET_READING_FAILED'); }
  async listReadingRecordsForUser(userId) { userId = requiredString(userId, 'INVALID_USER_ID'); return execute(async () => freeze(await Promise.all((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where user_id=$1 order by created_at desc,id asc`, [userId])).rows.map((row) => readingFromRow(row, this.codec)))), 'LIST_READINGS_FAILED'); }
  async listReadingRecordsForBirthProfile(birthProfileId) { birthProfileId = requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID'); return execute(async () => freeze(await Promise.all((await this.db.query(`select ${READING_COLUMNS} from app.reading_records where birth_profile_id=$1 order by created_at desc,id asc`, [birthProfileId])).rows.map((row) => readingFromRow(row, this.codec)))), 'LIST_READINGS_FAILED'); }
  async archiveReadingRecord(readingId, archivedAt) { readingId = requiredString(readingId, 'INVALID_READING_ID'); return execute(async () => readingFromRow(await queryOne(this.db, `update app.reading_records set archived_at=$2 where id=$1 returning ${READING_COLUMNS}`, [readingId, canonicalTime(archivedAt, 'INVALID_ARCHIVED_AT')], 'READING_NOT_FOUND'), this.codec), 'ARCHIVE_READING_FAILED'); }
}

class PostgresEntitlementRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresEntitlementRepository({ db }); }
  async createEntitlement(input = {}) { const id = requiredString(input.id, 'INVALID_ENTITLEMENT_ID'); const validFrom = canonicalTime(input.validFrom, 'INVALID_ENTITLEMENT_VALIDITY'); const validUntil = input.validUntil == null ? null : canonicalTime(input.validUntil, 'INVALID_ENTITLEMENT_VALIDITY'); if (validUntil && Date.parse(validUntil) <= Date.parse(validFrom)) fail('INVALID_ENTITLEMENT_VALIDITY'); const createdAt = input.createdAt == null ? now() : canonicalTime(input.createdAt); const updatedAt = input.updatedAt == null ? createdAt : canonicalTime(input.updatedAt); return execute(async () => entitlementFromRow((await this.db.query(`insert into app.entitlements (${ENTITLEMENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning ${ENTITLEMENT_COLUMNS}`, [id, requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.productKey, 'INVALID_PRODUCT_KEY'), requiredString(input.status || 'active', 'INVALID_STATUS'), input.quantity, validFrom, validUntil, requiredNullableId(input.sourcePaymentTransactionId, 'INVALID_PAYMENT_TRANSACTION_ID'), createdAt, updatedAt])).rows[0]), 'CREATE_ENTITLEMENT_FAILED'); }
  async getEntitlement(id) { id = requiredString(id, 'INVALID_ENTITLEMENT_ID'); return execute(async () => entitlementFromRow(await queryOne(this.db, `select ${ENTITLEMENT_COLUMNS} from app.entitlements where id=$1`, [id], 'ENTITLEMENT_NOT_FOUND')), 'GET_ENTITLEMENT_FAILED'); }
  async listActiveEntitlementsForUser(userId, evaluationTime) { userId = requiredString(userId, 'INVALID_USER_ID'); const at = canonicalTime(evaluationTime, 'INVALID_EVALUATION_TIME'); return execute(async () => freeze((await this.db.query(`select ${ENTITLEMENT_COLUMNS} from app.entitlements where user_id=$1 and status='active' and quantity>0 and valid_from <= $2 and (valid_until is null or valid_until > $2) order by valid_from asc,id asc`, [userId, at])).rows.map(entitlementFromRow)), 'LIST_ENTITLEMENTS_FAILED'); }
  async consumeEntitlement(id, evaluationTime) { id = requiredString(id, 'INVALID_ENTITLEMENT_ID'); const at = canonicalTime(evaluationTime, 'INVALID_EVALUATION_TIME'); return execute(async () => { const updated = await this.db.query(`update app.entitlements set quantity=quantity-1,updated_at=$2 where id=$1 and quantity>0 and status='active' and valid_from <= $2 and (valid_until is null or valid_until > $2) returning ${ENTITLEMENT_COLUMNS}`, [id, at]); if (updated.rows.length) return entitlementFromRow(updated.rows[0]); const prior = await this.db.query(`select status,quantity,valid_from,valid_until from app.entitlements where id=$1`, [id]); if (!prior.rows.length) fail('ENTITLEMENT_NOT_FOUND'); const row = prior.rows[0]; if (row.status !== 'active') fail('ENTITLEMENT_INACTIVE'); if (Date.parse(row.valid_from) > Date.parse(at) || (row.valid_until && Date.parse(row.valid_until) <= Date.parse(at))) fail('ENTITLEMENT_EXPIRED'); fail('ENTITLEMENT_EXHAUSTED'); }, 'CONSUME_ENTITLEMENT_FAILED'); }
}

class PostgresCareerEventRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresCareerEventRepository({ db }); }
  async create(input = {}) { return execute(async () => careerEventFromRow((await this.db.query(`insert into app.career_events (${CAREER_EVENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning ${CAREER_EVENT_COLUMNS}`, [requiredString(input.id, 'INVALID_CAREER_EVENT_ID'), requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), requiredString(input.eventType, 'INVALID_CAREER_EVENT_TYPE'), requiredString(input.eventDatePrecision, 'INVALID_CAREER_EVENT_DATE'), input.eventYear, input.eventMonth, input.eventDay, input.title, input.notes, canonicalTime(input.createdAt), canonicalTime(input.updatedAt), null])).rows[0]), 'CREATE_CAREER_EVENT_FAILED'); }
  async listForProfile({ userId, birthProfileId } = {}) { return execute(async () => freeze((await this.db.query(`select ${CAREER_EVENT_COLUMNS} from app.career_events where user_id=$1 and birth_profile_id=$2 and deleted_at is null order by event_year asc,event_month asc nulls first,event_day asc nulls first,created_at asc,id asc`, [requiredString(userId, 'INVALID_USER_ID'), requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID')])).rows.map(careerEventFromRow)), 'LIST_CAREER_EVENTS_FAILED'); }
  async getForProfile({ userId, birthProfileId, id } = {}) { return execute(async () => careerEventFromRow(await queryOne(this.db, `select ${CAREER_EVENT_COLUMNS} from app.career_events where id=$1 and user_id=$2 and birth_profile_id=$3 and deleted_at is null`, [requiredString(id, 'INVALID_CAREER_EVENT_ID'), requiredString(userId, 'INVALID_USER_ID'), requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID')], 'CAREER_EVENT_NOT_FOUND')), 'GET_CAREER_EVENT_FAILED'); }
  async updateForProfile(input = {}) { return execute(async () => careerEventFromRow(await queryOne(this.db, `update app.career_events set event_type=$4,event_date_precision=$5,event_year=$6,event_month=$7,event_day=$8,title=$9,notes=$10,updated_at=$11 where id=$1 and user_id=$2 and birth_profile_id=$3 and deleted_at is null returning ${CAREER_EVENT_COLUMNS}`, [requiredString(input.id, 'INVALID_CAREER_EVENT_ID'), requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), requiredString(input.eventType, 'INVALID_CAREER_EVENT_TYPE'), requiredString(input.eventDatePrecision, 'INVALID_CAREER_EVENT_DATE'), input.eventYear, input.eventMonth, input.eventDay, input.title, input.notes, canonicalTime(input.updatedAt)], 'CAREER_EVENT_NOT_FOUND')), 'UPDATE_CAREER_EVENT_FAILED'); }
  async softDeleteForProfile({ userId, birthProfileId, id, deletedAt, updatedAt } = {}) { return execute(async () => careerEventFromRow(await queryOne(this.db, `update app.career_events set deleted_at=$4,updated_at=$5 where id=$1 and user_id=$2 and birth_profile_id=$3 and deleted_at is null returning ${CAREER_EVENT_COLUMNS}`, [requiredString(id, 'INVALID_CAREER_EVENT_ID'), requiredString(userId, 'INVALID_USER_ID'), requiredString(birthProfileId, 'INVALID_BIRTH_PROFILE_ID'), canonicalTime(deletedAt), canonicalTime(updatedAt)], 'CAREER_EVENT_NOT_FOUND')), 'DELETE_CAREER_EVENT_FAILED'); }
}

class PostgresPaymentRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresPaymentRepository({ db }); }
  async insertPaymentTransaction(input = {}) { const id = requiredString(input.id, 'INVALID_PAYMENT_TRANSACTION_ID'); if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor < 0 || typeof input.currency !== 'string' || !/^[A-Z]{3}$/.test(input.currency)) fail('INVALID_PAYMENT_AMOUNT'); const createdAt = canonicalTime(input.createdAt); const updatedAt = input.updatedAt == null ? createdAt : canonicalTime(input.updatedAt); return execute(async () => paymentFromRow((await this.db.query(`insert into app.payment_transactions (${PAYMENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning ${PAYMENT_COLUMNS}`, [id, requiredString(input.userId, 'INVALID_USER_ID'), requiredString(input.provider, 'INVALID_PAYMENT_PROVIDER'), requiredString(input.providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID'), requiredString(input.status || 'created', 'INVALID_STATUS'), input.amountMinor, input.currency, createdAt, updatedAt])).rows[0]), 'INSERT_PAYMENT_FAILED'); }
  async getPaymentTransaction(id) { id = requiredString(id, 'INVALID_PAYMENT_TRANSACTION_ID'); return execute(async () => paymentFromRow(await queryOne(this.db, `select ${PAYMENT_COLUMNS} from app.payment_transactions where id=$1`, [id], 'PAYMENT_TRANSACTION_NOT_FOUND')), 'GET_PAYMENT_FAILED'); }
  async findByProviderTransactionId(provider, providerTransactionId) { provider = requiredString(provider, 'INVALID_PAYMENT_PROVIDER'); providerTransactionId = requiredString(providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID'); return execute(async () => { const result = await this.db.query(`select ${PAYMENT_COLUMNS} from app.payment_transactions where provider=$1 and provider_transaction_id=$2`, [provider, providerTransactionId]); return result.rows.length ? paymentFromRow(result.rows[0]) : null; }, 'FIND_PAYMENT_FAILED'); }
}

class PostgresPurchaseRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresPurchaseRepository({ db }); }
  async findByProviderTransaction({ provider, environment, providerTransactionId } = {}) { return execute(async () => { const result = await this.db.query(`select ${PURCHASE_COLUMNS} from app.purchase_records where provider=$1 and environment=$2 and provider_transaction_id=$3`, [requiredString(provider, 'INVALID_PURCHASE_PROVIDER'), requiredString(environment, 'INVALID_PURCHASE_ENVIRONMENT'), requiredString(providerTransactionId, 'INVALID_PROVIDER_TRANSACTION_ID')]); return result.rows.length ? purchaseFromRow(result.rows[0]) : null; }, 'FIND_PURCHASE_FAILED'); }
  async insert(input = {}) { const item = purchaseRecord(input); return execute(async () => { const existing = await this.findByProviderTransaction(item); if (existing) { if (existing.userId !== item.userId) fail('PURCHASE_OWNERSHIP_CONFLICT'); return existing; } return purchaseFromRow((await this.db.query(`insert into app.purchase_records (${PURCHASE_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) returning ${PURCHASE_COLUMNS}`, [item.id,item.userId,item.provider,item.environment,item.productId,item.providerTransactionId,item.originalTransactionId,item.status,item.purchasedAt,item.validFrom,item.validUntil,item.verifiedAt,item.paymentTransactionId,item.createdAt,item.updatedAt])).rows[0]); }, 'INSERT_PURCHASE_FAILED'); }
  async listForUser(userId) { return execute(async () => freeze((await this.db.query(`select ${PURCHASE_COLUMNS} from app.purchase_records where user_id=$1 order by purchased_at desc,id asc`, [requiredString(userId, 'INVALID_USER_ID')])).rows.map(purchaseFromRow)), 'LIST_PURCHASES_FAILED'); }
}

class PostgresSubscriptionRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresSubscriptionRepository({ db }); }
  async findByProviderOriginalTransaction({ provider, environment, originalTransactionId } = {}) { return execute(async () => { const result = await this.db.query(`select ${SUBSCRIPTION_COLUMNS} from app.subscription_records where provider=$1 and environment=$2 and original_transaction_id=$3`, [requiredString(provider, 'INVALID_PURCHASE_PROVIDER'), requiredString(environment, 'INVALID_PURCHASE_ENVIRONMENT'), requiredString(originalTransactionId, 'INVALID_ORIGINAL_TRANSACTION_ID')]); return result.rows.length ? subscriptionFromRow(result.rows[0]) : null; }, 'FIND_SUBSCRIPTION_FAILED'); }
  async findUsableCandidatesForUser(userId, at) { return execute(async () => freeze((await this.db.query(`select ${SUBSCRIPTION_COLUMNS} from app.subscription_records where user_id=$1 and valid_from <= $2 and valid_until > $2 and status in ('ACTIVE','GRACE_PERIOD','CANCELED') order by valid_until desc,id asc`, [requiredString(userId, 'INVALID_USER_ID'), canonicalTime(at, 'INVALID_EVALUATION_TIME')])).rows.map(subscriptionFromRow)), 'LIST_SUBSCRIPTIONS_FAILED'); }
  async upsertVerifiedState(input = {}) { const item = subscriptionRecord(input); return execute(async () => { const existing = await this.findByProviderOriginalTransaction(item); if (existing && existing.userId !== item.userId) fail('PURCHASE_OWNERSHIP_CONFLICT'); if (existing && existing.providerEventTime && item.providerEventTime && Date.parse(item.providerEventTime) < Date.parse(existing.providerEventTime)) return existing; if (existing) return subscriptionFromRow((await this.db.query(`update app.subscription_records set status=$2,valid_from=$3,valid_until=$4,auto_renew_enabled=$5,grace_until=$6,canceled_at=$7,revoked_at=$8,refunded_at=$9,latest_purchase_record_id=$10,provider_event_time=$11,provider_event_version=$12,updated_at=$13 where id=$1 returning ${SUBSCRIPTION_COLUMNS}`, [existing.id,item.status,item.validFrom,item.validUntil,item.autoRenewEnabled,item.graceUntil,item.canceledAt,item.revokedAt,item.refundedAt,item.latestPurchaseRecordId,item.providerEventTime,item.providerEventVersion,item.updatedAt])).rows[0]); return subscriptionFromRow((await this.db.query(`insert into app.subscription_records (${SUBSCRIPTION_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) returning ${SUBSCRIPTION_COLUMNS}`, [item.id,item.userId,item.provider,item.environment,item.productId,item.originalTransactionId,item.status,item.validFrom,item.validUntil,item.autoRenewEnabled,item.graceUntil,item.canceledAt,item.revokedAt,item.refundedAt,item.latestPurchaseRecordId,item.providerEventTime,item.providerEventVersion,item.createdAt,item.updatedAt])).rows[0]); }, 'UPSERT_SUBSCRIPTION_FAILED'); }
  async listForUser(userId) { return execute(async () => freeze((await this.db.query(`select ${SUBSCRIPTION_COLUMNS} from app.subscription_records where user_id=$1 order by valid_until desc,id asc`, [requiredString(userId, 'INVALID_USER_ID')])).rows.map(subscriptionFromRow)), 'LIST_SUBSCRIPTIONS_FAILED'); }
}

class PostgresPaymentEventRepository {
  constructor({ db } = {}) { this.db = dbBoundary(db); }
  withClient(db) { return new PostgresPaymentEventRepository({ db }); }
  async findByProviderEventId({ provider, environment, providerEventId } = {}) { return execute(async () => { const result = await this.db.query(`select ${EVENT_COLUMNS} from app.payment_events where provider=$1 and environment=$2 and provider_event_id=$3`, [requiredString(provider, 'INVALID_PURCHASE_PROVIDER'), requiredString(environment, 'INVALID_PURCHASE_ENVIRONMENT'), requiredString(providerEventId, 'INVALID_PROVIDER_EVENT_ID')]); return result.rows.length ? paymentEventFromRow(result.rows[0]) : null; }, 'FIND_PAYMENT_EVENT_FAILED'); }
  async insertReceived(input = {}) { const item = paymentEvent({ ...input, processingStatus: 'RECEIVED', processedAt: null, failureCode: null }); return execute(async () => { const existing = await this.findByProviderEventId(item); if (existing) return existing; return paymentEventFromRow((await this.db.query(`insert into app.payment_events (${EVENT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning ${EVENT_COLUMNS}`, [item.id,item.provider,item.environment,item.providerEventId,item.eventType,item.providerEventTime,item.purchaseRecordId,item.subscriptionRecordId,item.receivedAt,null,item.processingStatus,null,item.payloadDigest,item.createdAt])).rows[0]); }, 'INSERT_PAYMENT_EVENT_FAILED'); }
  async markProcessed(id, processedAt) { return execute(async () => paymentEventFromRow(await queryOne(this.db, `update app.payment_events set processing_status='PROCESSED',processed_at=$2,failure_code=null where id=$1 returning ${EVENT_COLUMNS}`, [requiredString(id, 'INVALID_PAYMENT_EVENT_ID'), canonicalTime(processedAt, 'INVALID_EVENT_TIMESTAMP')], 'PAYMENT_EVENT_NOT_FOUND')), 'UPDATE_PAYMENT_EVENT_FAILED'); }
  async markFailed(id, { processedAt, failureCode } = {}) { return execute(async () => paymentEventFromRow(await queryOne(this.db, `update app.payment_events set processing_status='FAILED',processed_at=$2,failure_code=$3 where id=$1 returning ${EVENT_COLUMNS}`, [requiredString(id, 'INVALID_PAYMENT_EVENT_ID'), canonicalTime(processedAt, 'INVALID_EVENT_TIMESTAMP'), requiredString(failureCode, 'INVALID_EVENT_FAILURE_CODE')], 'PAYMENT_EVENT_NOT_FOUND')), 'UPDATE_PAYMENT_EVENT_FAILED'); }
}

module.exports = { PostgresUserRepository, PostgresBirthProfileRepository, PostgresReadingRepository, PostgresEntitlementRepository, PostgresCareerEventRepository, PostgresPaymentRepository, PostgresPurchaseRepository, PostgresSubscriptionRepository, PostgresPaymentEventRepository, profileFingerprint, mapPostgresError };
