'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { createConclusion } = require('../../src/interpretation'); const { buildReading } = require('../../src/reading'); const { renderReading, getTemplate, validateTemplateText, TEMPLATE_SENTENCES, RENDERER_RULESET_ID } = require('../../src/rendering');
const START = { utc: '2024-01-01T00:00:00.000Z' }; const END = { utc: '2025-01-01T00:00:00.000Z' };
function deepFreeze(value) { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value).forEach(deepFreeze); } return value; }
function conclusion(topic, options = {}) { return createConclusion({ domain: 'CAREER', topic, rulesetId: 'test-ruleset', interpretiveRuleId: `rule:${topic}`, ruleClassification: options.classification || 'SOURCE_INTERPRETATION', conclusionStatus: options.status || 'SUPPORTED', evidenceIds: ['e'], rootSourceIds: ['root'], evidenceFamilyIds: ['family'], independentMechanismFamilies: ['NATAL_STRUCTURE'], sourceStrengths: ['CLASSICAL_TRANSLATION'], contradictions: options.contradictions || [], unresolvedEvidenceIds: [], missingData: options.missingData || [], temporalContext: options.temporalContext || { dashaIntervals: [], gocharSnapshotInstant: null, transitEventIds: [] }, provenance: { sourceRefs: options.sourceRefs || ['source:test'], sourcePredicateId: options.sourcePredicateId || null } }); }
function reading(conclusions) { return buildReading({ domain: 'CAREER', conclusions }); }
function item(rendered, topic) { return rendered.sections.flatMap((section) => section.items).find((value) => value.topic === topic); }

test('renders a valid Career reading only in en-IN and rejects unsupported inputs', () => { const result = renderReading({ reading: reading([conclusion('CAREER_H10_SIGNIFICATION_SCOPE_PRESENT')]), locale: 'en-IN' }); assert.equal(result.domain, 'CAREER'); assert.throws(() => renderReading({ reading: result, locale: 'en' }), /Unsupported locale/); assert.throws(() => renderReading({ reading: { domain: 'HEALTH', sections: [] }, locale: 'en-IN' }), /CAREER/); });
test('uses only allowlisted templates and validates unsafe template text', () => { assert.ok(getTemplate('CAREER_H10_SIGNIFICATION_SCOPE_PRESENT')); assert.throws(() => getTemplate('UNKNOWN_TEMPLATE'), /Unknown/); assert.throws(() => validateTemplateText('This is likely a strong career period.'), /forbidden/); assert.equal(Object.isFrozen(TEMPLATE_SENTENCES), true); });
test('renders neutral H10, H2, H11, Dasha, Gochar, transit, and co-activation sentences', () => { const context = { dashaIntervals: [{ level: 'MD', lord: 'Venus', startInstant: START, endInstant: END }], gocharSnapshotInstant: '2024-06-01T00:00:00.000Z', transitEventIds: ['event:exact'] }; const rendered = renderReading({ locale: 'en-IN', reading: reading(['CAREER_H10_SIGNIFICATION_SCOPE_PRESENT', 'CAREER_H10_LORD_NATAL_CONNECTION_PRESENT', 'CAREER_H10_OCCUPANT_CONNECTION_PRESENT', 'CAREER_H2_RESOURCE_CONTEXT_PRESENT', 'CAREER_H11_GAIN_CONTEXT_PRESENT', 'CAREER_H10_CONNECTED_DASHA_ACTIVATION_PRESENT', 'CAREER_GOCHAR_CONNECTION_PRESENT', 'CAREER_TIMING_TRIGGER_CONTEXT_PRESENT', 'CAREER_TEMPORAL_COACTIVATION_PRESENT'].map((topic) => conclusion(topic, { temporalContext: context }))) }); assert.match(item(rendered, 'CAREER_H10_SIGNIFICATION_SCOPE_PRESENT').sentence, /10th house/); assert.match(item(rendered, 'CAREER_H2_RESOURCE_CONTEXT_PRESENT').sentence, /resource context/); assert.match(item(rendered, 'CAREER_H11_GAIN_CONTEXT_PRESENT').sentence, /gains context/); assert.deepEqual(item(rendered, 'CAREER_H10_CONNECTED_DASHA_ACTIVATION_PRESENT').temporalDisplay, context); assert.equal(item(rendered, 'CAREER_TIMING_TRIGGER_CONTEXT_PRESENT').temporalDisplay.transitEventIds[0], 'event:exact'); const text = JSON.stringify(rendered); for (const word of ['salary', 'promotion', 'favorable', 'unfavorable', 'confidence', 'strong indicators']) assert.equal(text.includes(word), false, word); });
test('renders the classical predicate with mandatory safe disclosures and supplied classical title only', () => { const rendered = renderReading({ locale: 'en-IN', reading: reading([conclusion('CAREER_CLASSICAL_PROFESSIONAL_LOSS_PREDICATE_PRESENT', { classification: 'CLASSICAL_RULE', sourceRefs: ['BPHS:Chapter-60'], sourcePredicateId: 'bphs-venus-saturn-professional-loss-natal-v1' })]) }); const value = rendered.sections[0].items[0]; assert.match(value.sentence, /audited BPHS/); assert.equal(value.sourceAttribution.title, 'Brihat Parashara Hora Shastra'); assert.ok(value.disclosures.some((entry) => entry.code === 'CLASSICAL_PREDICATE_NOT_EVENT_CERTAINTY')); assert.ok(value.disclosures.some((entry) => entry.code === 'NO_OUTCOME_GUARANTEE')); assert.ok(value.disclosures.some((entry) => entry.code === 'NO_PROBABILITY_ASSESSMENT')); const text = [value.sentence, ...value.disclosures.map((entry) => entry.statement)].join(' ').toLowerCase(); for (const word of ['job loss', 'will lose', 'likely', 'chance', 'probability', 'risk', 'warning']) assert.equal(text.includes(word), false, word); });
test('preserves all statuses, disclosures, temporal values, and neutral wording', () => { const statuses = ['CONTRADICTED', 'INSUFFICIENT_EVIDENCE', 'NOT_APPLICABLE', 'MIXED']; const rendered = renderReading({ locale: 'en-IN', reading: reading(statuses.map((status) => conclusion('CAREER_H10_SIGNIFICATION_SCOPE_PRESENT', { status, contradictions: status === 'CONTRADICTED' ? ['c'] : [], missingData: status === 'INSUFFICIENT_EVIDENCE' ? ['m'] : [] }))) }); const all = rendered.sections.flatMap((section) => section.items); assert.deepEqual(all.map((value) => value.status).sort(), statuses.sort()); assert.ok(all.some((value) => value.sentence.includes('explicit contradiction'))); assert.ok(all.some((value) => value.sentence.includes('insufficient'))); assert.ok(all.some((value) => value.sentence.includes('does not satisfy'))); assert.ok(all.some((value) => value.sentence.includes('differing supported contexts'))); });
test('preserves Layer 14A order, deduplicates items, is deterministic and immutable, and has no model/network dependency', () => { const first = conclusion('CAREER_GOCHAR_CONNECTION_PRESENT'); const second = conclusion('CAREER_H10_SIGNIFICATION_SCOPE_PRESENT'); const source = deepFreeze(reading([second, first, first])); const before = JSON.stringify(source); const left = renderReading({ reading: source, locale: 'en-IN' }); const right = renderReading({ reading: source, locale: 'en-IN' }); assert.deepEqual(left, right); assert.equal(left.sections.flatMap((section) => section.items).length, 2); assert.equal(left.sections[0].section, 'CAREER_STRUCTURE'); assert.equal(Object.isFrozen(left), true); assert.equal(Object.isFrozen(left.sections[0].items[0]), true); assert.equal(JSON.stringify(source), before); assert.equal(left.provenance.rendererRulesetId, RENDERER_RULESET_ID); const text = JSON.stringify(left); for (const key of ['score', 'confidence', 'recommendation', 'remedy', 'network', 'openai', 'anthropic']) assert.equal(text.includes(`"${key}"`), false, key); });
